// Package catalogue holds the entities a project's book is made of, and the
// rules about them that need no I/O.
//
// This package is pure: it reads no clock, no environment and no database
// (backend ADR 0001).
package catalogue

import (
	"errors"
	"strings"
	"time"

	"github.com/haribo/ozalid/apps/server/internal/domain/review"
)

// Errors the domain can state on its own, without asking anything.
var (
	ErrTitleRequired       = errors.New("catalogue: a case needs a title")
	ErrNameRequired        = errors.New("catalogue: a category needs a name")
	ErrCategoryNotEmpty    = errors.New("catalogue: only an empty category can be deleted")
	ErrCaseAlreadyArchived = errors.New("catalogue: the case is already archived")
)

// IntakePolicy governs whether a run may be taken in while reviews are open
// (ADR 0007).
type IntakePolicy string

const (
	// PolicyStrict refuses intake while any case is to-review.
	PolicyStrict IntakePolicy = "strict"
	// PolicyPerCase always accepts; each case keeps pointing at the edition
	// its reviewer is judging.
	PolicyPerCase IntakePolicy = "per-case"
)

// Valid reports whether p is a policy the product implements.
func (p IntakePolicy) Valid() bool {
	return p == PolicyStrict || p == PolicyPerCase
}

// Project is a product under review. It owns its own cases, axes and storage.
type Project struct {
	ID           string
	Slug         string
	Name         string
	IntakePolicy IntakePolicy
	CreatedAt    time.Time
	// People and Programs are how many of each reach this project. Deactivated
	// accounts are not counted: they reach nothing (product.md §8.2).
	People   int
	Programs int
}

// Category is a node in the catalogue tree. A case belongs to exactly one
// (ADR 0014).
type Category struct {
	ID       string
	ParentID *string
	Name     string
	Position int32
}

// Case is one reviewable user flow.
//
// Its id is generated by the server and never changes; title and description
// are ordinary mutable attributes (ADR 0014).
type Case struct {
	ID          string
	ProjectID   string
	CategoryID  *string
	Title       string
	Description *string
	// State is computed by the server from the case's comments and is never
	// received from a client (ADR 0002, ADR 0012).
	State      review.CaseState
	ArchivedAt *time.Time
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// Archived reports whether the case has left the catalogue. An archived case
// stays readable with its captures, comments and journal (ADR 0014).
func (c Case) Archived() bool { return c.ArchivedAt != nil }

// Axis is a rendering dimension the project declares. ozalid ships no list:
// an axis exists because a capture mentioned it (ADR 0001).
type Axis struct {
	Name     string
	Position int32
}

// StateCounts is how many cases sit in each state under something — a
// category's whole descendance, or a project.
type StateCounts struct {
	NotInstrumented int64
	ToReview        int64
	ToFix           int64
	Reviewed        int64
}

// Total is how many cases the counts cover.
func (c StateCounts) Total() int64 {
	return c.NotInstrumented + c.ToReview + c.ToFix + c.Reviewed
}

// CategoryNode is a category with what its whole branch holds.
type CategoryNode struct {
	Category
	Cases        StateCounts
	LastActivity *time.Time
}

// CaptureCounts is how a case's captures stand at the edition it points at.
type CaptureCounts struct {
	Total     int64
	Validated int64
	Commented int64
	ToJudge   int64
}

// CaseSummary is a case plus what a listing needs to draw its row without
// asking a second question.
type CaseSummary struct {
	Case
	Captures    CaptureCounts
	LastEdition *time.Time
}

// CleanTitle trims a title and reports whether anything is left. A title of
// spaces is a missing title.
func CleanTitle(s string) (string, error) {
	t := strings.TrimSpace(s)
	if t == "" {
		return "", ErrTitleRequired
	}
	return t, nil
}

// CleanName does the same for a category name.
func CleanName(s string) (string, error) {
	n := strings.TrimSpace(s)
	if n == "" {
		return "", ErrNameRequired
	}
	return n, nil
}
