// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlcgen

import (
	"context"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, service_account_id, rights)
VALUES ($1, $2, $3, $4)
`

type AddProjectMemberParams struct {
	ProjectID        string
	UserID           *string
	ServiceAccountID *string
	Rights           string
}

// A service account's project is written here and nowhere else, so the two can
// never disagree; the partial unique index keeps it to one (ADR 0018).
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.ServiceAccountID,
		arg.Rights,
	)
	return err
}

const claimSignInLink = `-- name: ClaimSignInLink :one
UPDATE sign_in_links
SET used_at = now()
WHERE link_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

// A link is found by its hash, and only if it is still good. Expired and
// already used are both refused here rather than reported to the caller: what
// reaches the browser is one answer, "this link no longer works".
func (q *Queries) ClaimSignInLink(ctx context.Context, linkHash string) (string, error) {
	row := q.db.QueryRow(ctx, claimSignInLink, linkHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at
`

type CreateServiceAccountParams struct {
	Name    string
	OwnerID string
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount, arg.Name, arg.OwnerID)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
	)
	return i, err
}

const createServiceToken = `-- name: CreateServiceToken :one
INSERT INTO service_tokens (service_account_id, label, token_hash)
VALUES ($1, $2, $3)
RETURNING id, service_account_id, label, token_hash, created_at, last_used_at
`

type CreateServiceTokenParams struct {
	ServiceAccountID string
	Label            string
	TokenHash        string
}

func (q *Queries) CreateServiceToken(ctx context.Context, arg CreateServiceTokenParams) (ServiceToken, error) {
	row := q.db.QueryRow(ctx, createServiceToken, arg.ServiceAccountID, arg.Label, arg.TokenHash)
	var i ServiceToken
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.Label,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::int))
`

type CreateSessionParams struct {
	UserID          string
	TokenHash       string
	LifetimeSeconds int32
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.LifetimeSeconds)
	return err
}

const createSignInLink = `-- name: CreateSignInLink :exec
INSERT INTO sign_in_links (user_id, link_hash, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::int))
`

type CreateSignInLinkParams struct {
	UserID          string
	LinkHash        string
	LifetimeSeconds int32
}

// The expiry is computed by the database, against the clock that will later
// decide whether the link is still good. Setting it from the application would
// compare one clock against another, and clock skew would decide.
func (q *Queries) CreateSignInLink(ctx context.Context, arg CreateSignInLinkParams) error {
	_, err := q.db.Exec(ctx, createSignInLink, arg.UserID, arg.LinkHash, arg.LifetimeSeconds)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, is_admin)
VALUES ($1, $2, $3)
RETURNING id, name, email, is_admin, deactivated_at, created_at
`

type CreateUserParams struct {
	Name    string
	Email   string
	IsAdmin bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users SET deactivated_at = now() WHERE id = $1
`

// An account is deactivated, never deleted: what it reviewed has to stay
// readable, and the journal names it (ADR 0018).
func (q *Queries) DeactivateUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const endSession = `-- name: EndSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) EndSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, endSession, tokenHash)
	return err
}

const serviceAccountByTokenHash = `-- name: ServiceAccountByTokenHash :one
SELECT s.id, s.name, t.id AS token_id
FROM service_tokens t
JOIN service_accounts s ON s.id = t.service_account_id
WHERE t.token_hash = $1
`

type ServiceAccountByTokenHashRow struct {
	ID      string
	Name    string
	TokenID string
}

// The account a token opens, looked up by the hash kept for it.
//
// Nothing here compares the token itself: the hash is the key, so a lookup
// never carries a secret into a query plan or a slow-query log.
func (q *Queries) ServiceAccountByTokenHash(ctx context.Context, tokenHash string) (ServiceAccountByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, serviceAccountByTokenHash, tokenHash)
	var i ServiceAccountByTokenHashRow
	err := row.Scan(&i.ID, &i.Name, &i.TokenID)
	return i, err
}

const standingOfServiceAccount = `-- name: StandingOfServiceAccount :one
SELECT false AS is_admin, coalesce(m.rights, '')::text AS rights
FROM service_accounts s
LEFT JOIN project_members m
       ON m.service_account_id = s.id AND m.project_id = $2
WHERE s.id = $1
`

type StandingOfServiceAccountParams struct {
	ID        string
	ProjectID *string
}

type StandingOfServiceAccountRow struct {
	IsAdmin bool
	Rights  string
}

// What a program may do on one project.
//
// A service account never administers: administration reaches accounts, and a
// program that could make accounts could make itself another (product.md §8.2).
func (q *Queries) StandingOfServiceAccount(ctx context.Context, arg StandingOfServiceAccountParams) (StandingOfServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, standingOfServiceAccount, arg.ID, arg.ProjectID)
	var i StandingOfServiceAccountRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfServiceAccountOnSlug = `-- name: StandingOfServiceAccountOnSlug :one
SELECT false AS is_admin, coalesce(m.rights, '')::text AS rights
FROM service_accounts s
LEFT JOIN projects p ON p.slug = $2
LEFT JOIN project_members m ON m.service_account_id = s.id AND m.project_id = p.id
WHERE s.id = $1
`

type StandingOfServiceAccountOnSlugParams struct {
	ID   string
	Slug *string
}

type StandingOfServiceAccountOnSlugRow struct {
	IsAdmin bool
	Rights  string
}

func (q *Queries) StandingOfServiceAccountOnSlug(ctx context.Context, arg StandingOfServiceAccountOnSlugParams) (StandingOfServiceAccountOnSlugRow, error) {
	row := q.db.QueryRow(ctx, standingOfServiceAccountOnSlug, arg.ID, arg.Slug)
	var i StandingOfServiceAccountOnSlugRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfUser = `-- name: StandingOfUser :one
SELECT u.is_admin, coalesce(m.rights, '')::text AS rights
FROM users u
LEFT JOIN project_members m
       ON m.user_id = u.id AND m.project_id = $2
WHERE u.id = $1 AND u.deactivated_at IS NULL
`

type StandingOfUserParams struct {
	ID        string
	ProjectID *string
}

type StandingOfUserRow struct {
	IsAdmin bool
	Rights  string
}

func (q *Queries) StandingOfUser(ctx context.Context, arg StandingOfUserParams) (StandingOfUserRow, error) {
	row := q.db.QueryRow(ctx, standingOfUser, arg.ID, arg.ProjectID)
	var i StandingOfUserRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfUserOnSlug = `-- name: StandingOfUserOnSlug :one
SELECT u.is_admin, coalesce(m.rights, '')::text AS rights
FROM users u
LEFT JOIN projects p ON p.slug = $2
LEFT JOIN project_members m ON m.user_id = u.id AND m.project_id = p.id
WHERE u.id = $1 AND u.deactivated_at IS NULL
`

type StandingOfUserOnSlugParams struct {
	ID   string
	Slug *string
}

type StandingOfUserOnSlugRow struct {
	IsAdmin bool
	Rights  string
}

// What a person may do on one project: whether they administer the instance,
// and what their membership carries. A deactivated account resolves to nothing.
// The same two questions, asked by the slug a caller names rather than by an id
// it has no way to know. A slug nobody has resolves to nothing, which the rule
// then refuses — the same answer as an unknown project by a shorter road.
func (q *Queries) StandingOfUserOnSlug(ctx context.Context, arg StandingOfUserOnSlugParams) (StandingOfUserOnSlugRow, error) {
	row := q.db.QueryRow(ctx, standingOfUserOnSlug, arg.ID, arg.Slug)
	var i StandingOfUserOnSlugRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const touchServiceToken = `-- name: TouchServiceToken :exec
UPDATE service_tokens SET last_used_at = now() WHERE id = $1
`

// Read on every accepted call, so an operator can tell which tokens are still
// in use and which can go.
func (q *Queries) TouchServiceToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchServiceToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, name, email, is_admin, deactivated_at, created_at FROM users WHERE lower(email) = lower($1) AND deactivated_at IS NULL
`

func (q *Queries) UserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, name, email, is_admin, deactivated_at, created_at FROM users WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const userBySessionToken = `-- name: UserBySessionToken :one
SELECT u.id, s.id AS session_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now() AND u.deactivated_at IS NULL
`

type UserBySessionTokenRow struct {
	ID        string
	SessionID string
}

// The account a session belongs to, provided both are still good. A deactivated
// account resolves to nothing, so shutting an account shuts its sessions in the
// same instant.
func (q *Queries) UserBySessionToken(ctx context.Context, tokenHash string) (UserBySessionTokenRow, error) {
	row := q.db.QueryRow(ctx, userBySessionToken, tokenHash)
	var i UserBySessionTokenRow
	err := row.Scan(&i.ID, &i.SessionID)
	return i, err
}
