// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: access.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addProjectMember = `-- name: AddProjectMember :exec
INSERT INTO project_members (project_id, user_id, service_account_id, rights)
VALUES ($1, $2, $3, $4)
`

type AddProjectMemberParams struct {
	ProjectID        string
	UserID           *string
	ServiceAccountID *string
	Rights           string
}

// A service account's project is written here and nowhere else, so the two can
// never disagree; the partial unique index keeps it to one (ADR 0018).
func (q *Queries) AddProjectMember(ctx context.Context, arg AddProjectMemberParams) error {
	_, err := q.db.Exec(ctx, addProjectMember,
		arg.ProjectID,
		arg.UserID,
		arg.ServiceAccountID,
		arg.Rights,
	)
	return err
}

const claimSignInLink = `-- name: ClaimSignInLink :one
UPDATE sign_in_links
SET used_at = now()
WHERE link_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

// A link is found by its hash, and only if it is still good. Expired and
// already used are both refused here rather than reported to the caller: what
// reaches the browser is one answer, "this link no longer works".
func (q *Queries) ClaimSignInLink(ctx context.Context, linkHash string) (string, error) {
	row := q.db.QueryRow(ctx, claimSignInLink, linkHash)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const createServiceAccount = `-- name: CreateServiceAccount :one
INSERT INTO service_accounts (name, owner_id)
VALUES ($1, $2)
RETURNING id, name, owner_id, created_at, deactivated_at
`

type CreateServiceAccountParams struct {
	Name    string
	OwnerID string
}

func (q *Queries) CreateServiceAccount(ctx context.Context, arg CreateServiceAccountParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccount, arg.Name, arg.OwnerID)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const createServiceAccountInProject = `-- name: CreateServiceAccountInProject :one
INSERT INTO service_accounts (name, owner_id)
SELECT $1, $2
WHERE EXISTS (SELECT 1 FROM projects WHERE slug = $3)
RETURNING id, name, owner_id, created_at, deactivated_at
`

type CreateServiceAccountInProjectParams struct {
	Name    string
	OwnerID string
	Slug    string
}

func (q *Queries) CreateServiceAccountInProject(ctx context.Context, arg CreateServiceAccountInProjectParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, createServiceAccountInProject, arg.Name, arg.OwnerID, arg.Slug)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const createServiceToken = `-- name: CreateServiceToken :one
INSERT INTO service_tokens (service_account_id, label, token_hash)
VALUES ($1, $2, $3)
RETURNING id, service_account_id, label, token_hash, created_at, last_used_at
`

type CreateServiceTokenParams struct {
	ServiceAccountID string
	Label            string
	TokenHash        string
}

func (q *Queries) CreateServiceToken(ctx context.Context, arg CreateServiceTokenParams) (ServiceToken, error) {
	row := q.db.QueryRow(ctx, createServiceToken, arg.ServiceAccountID, arg.Label, arg.TokenHash)
	var i ServiceToken
	err := row.Scan(
		&i.ID,
		&i.ServiceAccountID,
		&i.Label,
		&i.TokenHash,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::int))
`

type CreateSessionParams struct {
	UserID          string
	TokenHash       string
	LifetimeSeconds int32
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.UserID, arg.TokenHash, arg.LifetimeSeconds)
	return err
}

const createSignInLink = `-- name: CreateSignInLink :exec
INSERT INTO sign_in_links (user_id, link_hash, expires_at)
VALUES ($1, $2, now() + make_interval(secs => $3::int))
`

type CreateSignInLinkParams struct {
	UserID          string
	LinkHash        string
	LifetimeSeconds int32
}

// The expiry is computed by the database, against the clock that will later
// decide whether the link is still good. Setting it from the application would
// compare one clock against another, and clock skew would decide.
func (q *Queries) CreateSignInLink(ctx context.Context, arg CreateSignInLinkParams) error {
	_, err := q.db.Exec(ctx, createSignInLink, arg.UserID, arg.LinkHash, arg.LifetimeSeconds)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (name, email, is_admin)
VALUES ($1, $2, $3)
RETURNING id, name, email, is_admin, deactivated_at, created_at
`

type CreateUserParams struct {
	Name    string
	Email   string
	IsAdmin bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.Email, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deactivateServiceAccount = `-- name: DeactivateServiceAccount :execrows
UPDATE service_accounts sa
SET deactivated_at = coalesce(sa.deactivated_at, now())
FROM project_members m, projects p
WHERE sa.id = $1 AND m.service_account_id = sa.id
  AND p.id = m.project_id AND p.slug = $2
`

type DeactivateServiceAccountParams struct {
	ID   string
	Slug string
}

// Idempotent, like deactivating a person: the day it happened does not move.
func (q *Queries) DeactivateServiceAccount(ctx context.Context, arg DeactivateServiceAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateServiceAccount, arg.ID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deactivateUser = `-- name: DeactivateUser :execrows
UPDATE users SET deactivated_at = coalesce(deactivated_at, now()) WHERE id = $1
`

// An account is deactivated, never deleted: what it reviewed has to stay
// readable, and the journal names it (ADR 0018).
// Idempotent: `deactivated_at` is set once and never moved, so deactivating
// twice is not two different days.
func (q *Queries) DeactivateUser(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteServiceToken = `-- name: DeleteServiceToken :execrows
DELETE FROM service_tokens t
USING service_accounts sa, project_members m, projects p
WHERE t.id = $1 AND t.service_account_id = $2
  AND sa.id = t.service_account_id
  AND m.service_account_id = sa.id AND p.id = m.project_id AND p.slug = $3
`

type DeleteServiceTokenParams struct {
	ID               string
	ServiceAccountID string
	Slug             string
}

func (q *Queries) DeleteServiceToken(ctx context.Context, arg DeleteServiceTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteServiceToken, arg.ID, arg.ServiceAccountID, arg.Slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const endSession = `-- name: EndSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) EndSession(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, endSession, tokenHash)
	return err
}

const grantMembership = `-- name: GrantMembership :execrows
INSERT INTO project_members (project_id, user_id, rights)
SELECT p.id, u.id, $1
FROM projects p, users u
WHERE p.slug = $2 AND u.id = $3
ON CONFLICT (project_id, user_id) WHERE user_id IS NOT NULL
DO UPDATE SET rights = excluded.rights
`

type GrantMembershipParams struct {
	Rights string
	Slug   string
	UserID string
}

// Granting again changes the rights rather than failing: an administrator who
// meant to demote somebody said so, and refusing would make them revoke first.
func (q *Queries) GrantMembership(ctx context.Context, arg GrantMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, grantMembership, arg.Rights, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT
    coalesce(u.id, sa.id)     AS account_id,
    coalesce(u.name, sa.name) AS name,
    u.email,
    (m.user_id IS NOT NULL)::boolean AS is_person,
    m.rights,
    m.added_at,
    -- How many credentials this program holds. A program with none is a member
    -- that cannot authenticate — alive, and missing a key, which is a thing
    -- somebody can fix. NULL for a person, who presents no token.
    (SELECT count(*) FROM service_tokens t WHERE t.service_account_id = sa.id) AS tokens
FROM project_members m
JOIN projects p ON p.id = m.project_id
LEFT JOIN users u ON u.id = m.user_id
LEFT JOIN service_accounts sa ON sa.id = m.service_account_id
WHERE p.slug = $1
  AND coalesce(u.deactivated_at, sa.deactivated_at) IS NULL
ORDER BY is_person DESC, lower(coalesce(u.name, sa.name))
`

type ListProjectMembersRow struct {
	AccountID string
	Name      string
	Email     *string
	IsPerson  bool
	Rights    string
	AddedAt   pgtype.Timestamptz
	Tokens    int64
}

// Both kinds of holder in one list: a project's members are the people and the
// programs that reach it, and hiding either would make the list a lie.
// A deactivated account is not listed. This page answers "who reaches this
// project", and a deactivated account reaches nothing; it stays on /accounts,
// which answers "who exists on this instance" (product.md §8.2).
func (q *Queries) ListProjectMembers(ctx context.Context, slug string) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectMembersRow{}
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.AccountID,
			&i.Name,
			&i.Email,
			&i.IsPerson,
			&i.Rights,
			&i.AddedAt,
			&i.Tokens,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServiceTokens = `-- name: ListServiceTokens :many
SELECT t.id, t.label, t.created_at, t.last_used_at
FROM service_tokens t
JOIN service_accounts sa ON sa.id = t.service_account_id
JOIN project_members m ON m.service_account_id = sa.id
JOIN projects p ON p.id = m.project_id
WHERE t.service_account_id = $1 AND p.slug = $2
ORDER BY t.created_at DESC
`

type ListServiceTokensParams struct {
	ServiceAccountID string
	Slug             string
}

type ListServiceTokensRow struct {
	ID         string
	Label      string
	CreatedAt  pgtype.Timestamptz
	LastUsedAt pgtype.Timestamptz
}

// What a token is for and whether anything still uses it. Never the token: only
// its hash was ever stored, and a hash is not a credential anyone can present.
func (q *Queries) ListServiceTokens(ctx context.Context, arg ListServiceTokensParams) ([]ListServiceTokensRow, error) {
	rows, err := q.db.Query(ctx, listServiceTokens, arg.ServiceAccountID, arg.Slug)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListServiceTokensRow{}
	for rows.Next() {
		var i ListServiceTokensRow
		if err := rows.Scan(
			&i.ID,
			&i.Label,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, is_admin, deactivated_at, created_at FROM users ORDER BY lower(name), id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsAdmin,
			&i.DeactivatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsForServiceAccount = `-- name: ProjectsForServiceAccount :many
SELECT p.id, p.slug, p.name, p.intake_policy, p.created_at, p.pixel_threshold,
    (SELECT count(*) FROM project_members pm
      LEFT JOIN users pu ON pu.id = pm.user_id
      WHERE pm.project_id = p.id AND pm.user_id IS NOT NULL
        AND pu.deactivated_at IS NULL) AS people,
    (SELECT count(*) FROM project_members pm
      LEFT JOIN service_accounts ps ON ps.id = pm.service_account_id
      WHERE pm.project_id = p.id AND pm.service_account_id IS NOT NULL
        AND ps.deactivated_at IS NULL) AS programs
FROM projects p
JOIN project_members m ON m.project_id = p.id
WHERE m.service_account_id = $1
ORDER BY lower(p.name)
`

type ProjectsForServiceAccountRow struct {
	ID             string
	Slug           string
	Name           string
	IntakePolicy   string
	CreatedAt      pgtype.Timestamptz
	PixelThreshold int32
	People         int64
	Programs       int64
}

// A service account belongs to one project and sees that one (ADR 0018).
func (q *Queries) ProjectsForServiceAccount(ctx context.Context, serviceAccountID *string) ([]ProjectsForServiceAccountRow, error) {
	rows, err := q.db.Query(ctx, projectsForServiceAccount, serviceAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsForServiceAccountRow{}
	for rows.Next() {
		var i ProjectsForServiceAccountRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IntakePolicy,
			&i.CreatedAt,
			&i.PixelThreshold,
			&i.People,
			&i.Programs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectsForUser = `-- name: ProjectsForUser :many
SELECT p.id, p.slug, p.name, p.intake_policy, p.created_at, p.pixel_threshold,
    (SELECT count(*) FROM project_members pm
      LEFT JOIN users pu ON pu.id = pm.user_id
      LEFT JOIN service_accounts ps ON ps.id = pm.service_account_id
      WHERE pm.project_id = p.id
        AND coalesce(pu.deactivated_at, ps.deactivated_at) IS NULL
        AND pm.user_id IS NOT NULL) AS people,
    (SELECT count(*) FROM project_members pm
      LEFT JOIN service_accounts ps ON ps.id = pm.service_account_id
      WHERE pm.project_id = p.id AND pm.service_account_id IS NOT NULL
        AND ps.deactivated_at IS NULL) AS programs
FROM projects p
LEFT JOIN project_members m ON m.project_id = p.id AND m.user_id = $1
WHERE m.user_id IS NOT NULL OR $2::boolean
ORDER BY lower(p.name)
`

type ProjectsForUserParams struct {
	UserID  *string
	IsAdmin bool
}

type ProjectsForUserRow struct {
	ID             string
	Slug           string
	Name           string
	IntakePolicy   string
	CreatedAt      pgtype.Timestamptz
	PixelThreshold int32
	People         int64
	Programs       int64
}

// The projects a caller may see: the ones they belong to, and every one on the
// instance when they administer it. An administrator names a project to manage
// its membership, and a power that cannot be exercised is not a power
// (product.md §8.2). What stays withheld is everything inside.
func (q *Queries) ProjectsForUser(ctx context.Context, arg ProjectsForUserParams) ([]ProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, projectsForUser, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProjectsForUserRow{}
	for rows.Next() {
		var i ProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.IntakePolicy,
			&i.CreatedAt,
			&i.PixelThreshold,
			&i.People,
			&i.Programs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeMembership = `-- name: RevokeMembership :execrows
DELETE FROM project_members m
USING projects p
WHERE m.project_id = p.id AND p.slug = $1 AND m.user_id = $2
`

type RevokeMembershipParams struct {
	Slug   string
	UserID *string
}

func (q *Queries) RevokeMembership(ctx context.Context, arg RevokeMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeMembership, arg.Slug, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const serviceAccountByTokenHash = `-- name: ServiceAccountByTokenHash :one
SELECT s.id, s.name, t.id AS token_id
FROM service_tokens t
JOIN service_accounts s ON s.id = t.service_account_id
WHERE t.token_hash = $1 AND s.deactivated_at IS NULL
`

type ServiceAccountByTokenHashRow struct {
	ID      string
	Name    string
	TokenID string
}

// The account a token opens, looked up by the hash kept for it.
//
// Nothing here compares the token itself: the hash is the key, so a lookup
// never carries a secret into a query plan or a slow-query log.
// A deactivated service account resolves to nothing, exactly as a deactivated
// person does: the token still exists, and stops opening anything.
func (q *Queries) ServiceAccountByTokenHash(ctx context.Context, tokenHash string) (ServiceAccountByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, serviceAccountByTokenHash, tokenHash)
	var i ServiceAccountByTokenHashRow
	err := row.Scan(&i.ID, &i.Name, &i.TokenID)
	return i, err
}

const serviceAccountInProject = `-- name: ServiceAccountInProject :one
SELECT sa.id, sa.name, sa.owner_id, sa.created_at, sa.deactivated_at FROM service_accounts sa
JOIN project_members m ON m.service_account_id = sa.id
JOIN projects p ON p.id = m.project_id
WHERE sa.id = $1 AND p.slug = $2 AND sa.deactivated_at IS NULL
`

type ServiceAccountInProjectParams struct {
	ID   string
	Slug string
}

func (q *Queries) ServiceAccountInProject(ctx context.Context, arg ServiceAccountInProjectParams) (ServiceAccount, error) {
	row := q.db.QueryRow(ctx, serviceAccountInProject, arg.ID, arg.Slug)
	var i ServiceAccount
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.OwnerID,
		&i.CreatedAt,
		&i.DeactivatedAt,
	)
	return i, err
}

const standingOfServiceAccount = `-- name: StandingOfServiceAccount :one
SELECT false AS is_admin, coalesce(m.rights, '')::text AS rights
FROM service_accounts s
LEFT JOIN project_members m
       ON m.service_account_id = s.id AND m.project_id = $2
WHERE s.id = $1
`

type StandingOfServiceAccountParams struct {
	ID        string
	ProjectID *string
}

type StandingOfServiceAccountRow struct {
	IsAdmin bool
	Rights  string
}

// What a program may do on one project.
//
// A service account never administers: administration reaches accounts, and a
// program that could make accounts could make itself another (product.md §8.2).
func (q *Queries) StandingOfServiceAccount(ctx context.Context, arg StandingOfServiceAccountParams) (StandingOfServiceAccountRow, error) {
	row := q.db.QueryRow(ctx, standingOfServiceAccount, arg.ID, arg.ProjectID)
	var i StandingOfServiceAccountRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfServiceAccountOnSlug = `-- name: StandingOfServiceAccountOnSlug :one
SELECT false AS is_admin, coalesce(m.rights, '')::text AS rights
FROM service_accounts s
LEFT JOIN projects p ON p.slug = $2
LEFT JOIN project_members m ON m.service_account_id = s.id AND m.project_id = p.id
WHERE s.id = $1
`

type StandingOfServiceAccountOnSlugParams struct {
	ID   string
	Slug *string
}

type StandingOfServiceAccountOnSlugRow struct {
	IsAdmin bool
	Rights  string
}

func (q *Queries) StandingOfServiceAccountOnSlug(ctx context.Context, arg StandingOfServiceAccountOnSlugParams) (StandingOfServiceAccountOnSlugRow, error) {
	row := q.db.QueryRow(ctx, standingOfServiceAccountOnSlug, arg.ID, arg.Slug)
	var i StandingOfServiceAccountOnSlugRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfUser = `-- name: StandingOfUser :one
SELECT u.is_admin, coalesce(m.rights, '')::text AS rights
FROM users u
LEFT JOIN project_members m
       ON m.user_id = u.id AND m.project_id = $2
WHERE u.id = $1 AND u.deactivated_at IS NULL
`

type StandingOfUserParams struct {
	ID        string
	ProjectID *string
}

type StandingOfUserRow struct {
	IsAdmin bool
	Rights  string
}

func (q *Queries) StandingOfUser(ctx context.Context, arg StandingOfUserParams) (StandingOfUserRow, error) {
	row := q.db.QueryRow(ctx, standingOfUser, arg.ID, arg.ProjectID)
	var i StandingOfUserRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const standingOfUserOnSlug = `-- name: StandingOfUserOnSlug :one
SELECT u.is_admin, coalesce(m.rights, '')::text AS rights
FROM users u
LEFT JOIN projects p ON p.slug = $2
LEFT JOIN project_members m ON m.user_id = u.id AND m.project_id = p.id
WHERE u.id = $1 AND u.deactivated_at IS NULL
`

type StandingOfUserOnSlugParams struct {
	ID   string
	Slug *string
}

type StandingOfUserOnSlugRow struct {
	IsAdmin bool
	Rights  string
}

// What a person may do on one project: whether they administer the instance,
// and what their membership carries. A deactivated account resolves to nothing.
// The same two questions, asked by the slug a caller names rather than by an id
// it has no way to know. A slug nobody has resolves to nothing, which the rule
// then refuses — the same answer as an unknown project by a shorter road.
func (q *Queries) StandingOfUserOnSlug(ctx context.Context, arg StandingOfUserOnSlugParams) (StandingOfUserOnSlugRow, error) {
	row := q.db.QueryRow(ctx, standingOfUserOnSlug, arg.ID, arg.Slug)
	var i StandingOfUserOnSlugRow
	err := row.Scan(&i.IsAdmin, &i.Rights)
	return i, err
}

const touchServiceToken = `-- name: TouchServiceToken :exec
UPDATE service_tokens SET last_used_at = now() WHERE id = $1
`

// Read on every accepted call, so an operator can tell which tokens are still
// in use and which can go.
func (q *Queries) TouchServiceToken(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchServiceToken, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const userByEmail = `-- name: UserByEmail :one
SELECT id, name, email, is_admin, deactivated_at, created_at FROM users WHERE lower(email) = lower($1) AND deactivated_at IS NULL
`

func (q *Queries) UserByEmail(ctx context.Context, lower string) (User, error) {
	row := q.db.QueryRow(ctx, userByEmail, lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const userByID = `-- name: UserByID :one
SELECT id, name, email, is_admin, deactivated_at, created_at FROM users WHERE id = $1 AND deactivated_at IS NULL
`

func (q *Queries) UserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, userByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsAdmin,
		&i.DeactivatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const userBySessionToken = `-- name: UserBySessionToken :one
SELECT u.id, s.id AS session_id
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now() AND u.deactivated_at IS NULL
`

type UserBySessionTokenRow struct {
	ID        string
	SessionID string
}

// The account a session belongs to, provided both are still good. A deactivated
// account resolves to nothing, so shutting an account shuts its sessions in the
// same instant.
func (q *Queries) UserBySessionToken(ctx context.Context, tokenHash string) (UserBySessionTokenRow, error) {
	row := q.db.QueryRow(ctx, userBySessionToken, tokenHash)
	var i UserBySessionTokenRow
	err := row.Scan(&i.ID, &i.SessionID)
	return i, err
}
