// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: aggregates.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachCommentVariant = `-- name: AttachCommentVariant :exec
INSERT INTO comment_variants (comment_id, variant_id, capture_id)
SELECT $1, $2, (
    SELECT cap.id FROM captures cap
    JOIN comments c ON c.id = $1
    JOIN cases k ON k.id = c.case_id
    WHERE cap.step_id = c.step_id
      AND cap.variant_id = $2
      AND cap.edition_id = coalesce(
            k.current_edition_id,
            (SELECT e.id FROM editions e WHERE e.project_id = k.project_id
             ORDER BY e.created_at DESC, e.id DESC LIMIT 1))
)
ON CONFLICT DO NOTHING
`

type AttachCommentVariantParams struct {
	CommentID string
	VariantID string
}

// The anchor is the capture the reviewer was looking at: the one of the
// edition the case is judged against, for this step and variant. It is what
// the comment shows for as long as it lives — a step's name is a label, and
// positions shift (#132). Null when the step and variant had no capture, which is what
// there was to see.
func (q *Queries) AttachCommentVariant(ctx context.Context, arg AttachCommentVariantParams) error {
	_, err := q.db.Exec(ctx, attachCommentVariant, arg.CommentID, arg.VariantID)
	return err
}

const caseAcceptedCaptures = `-- name: CaseAcceptedCaptures :many
SELECT step_id, variant_id FROM capture_acceptances
WHERE case_id = $1
`

type CaseAcceptedCapturesRow struct {
	StepID    string
	VariantID string
}

func (q *Queries) CaseAcceptedCaptures(ctx context.Context, caseID string) ([]CaseAcceptedCapturesRow, error) {
	rows, err := q.db.Query(ctx, caseAcceptedCaptures, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseAcceptedCapturesRow{}
	for rows.Next() {
		var i CaseAcceptedCapturesRow
		if err := rows.Scan(&i.StepID, &i.VariantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseCaptureFacts = `-- name: CaseCaptureFacts :many
SELECT s.id AS step_id, c.variant_id, c.blob_hash, c.moved_pixels,
       coalesce(r.blob_hash, '') AS reference_hash
FROM steps s
JOIN captures c ON c.step_id = s.id AND c.edition_id = $2
LEFT JOIN LATERAL (
    SELECT ref.blob_hash FROM capture_references ref
    WHERE ref.case_id = s.case_id AND ref.step_id = s.id AND ref.variant_id = c.variant_id
      AND ref.environment_id = c.provenance->>'environmentId'
    ORDER BY ref.approved_at DESC LIMIT 1
) r ON true
WHERE s.case_id = $1
`

type CaseCaptureFactsParams struct {
	CaseID    string
	EditionID string
}

type CaseCaptureFactsRow struct {
	StepID        string
	VariantID     string
	BlobHash      string
	MovedPixels   *int32
	ReferenceHash string
}

// Everything the derivation reads about one case's captures (ADR 0021): the
// bytes on display, the reference approved in this capture's own environment
// (ADR 0017), and the measurement intake recorded.
func (q *Queries) CaseCaptureFacts(ctx context.Context, arg CaseCaptureFactsParams) ([]CaseCaptureFactsRow, error) {
	rows, err := q.db.Query(ctx, caseCaptureFacts, arg.CaseID, arg.EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseCaptureFactsRow{}
	for rows.Next() {
		var i CaseCaptureFactsRow
		if err := rows.Scan(
			&i.StepID,
			&i.VariantID,
			&i.BlobHash,
			&i.MovedPixels,
			&i.ReferenceHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseCaptures = `-- name: CaseCaptures :many
SELECT s.id AS step_id, c.variant_id
FROM steps s
JOIN captures c ON c.step_id = s.id AND c.edition_id = $2
WHERE s.case_id = $1
`

type CaseCapturesParams struct {
	CaseID    string
	EditionID string
}

type CaseCapturesRow struct {
	StepID    string
	VariantID string
}

// Everything the state computation reads, for one case at one edition.
func (q *Queries) CaseCaptures(ctx context.Context, arg CaseCapturesParams) ([]CaseCapturesRow, error) {
	rows, err := q.db.Query(ctx, caseCaptures, arg.CaseID, arg.EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseCapturesRow{}
	for rows.Next() {
		var i CaseCapturesRow
		if err := rows.Scan(&i.StepID, &i.VariantID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseCommentAnchors = `-- name: CaseCommentAnchors :many
SELECT cv.comment_id, c.step_id, cv.variant_id, a.blob_hash AS anchor_hash
FROM comment_variants cv
JOIN comments c ON c.id = cv.comment_id
LEFT JOIN captures a ON a.id = cv.capture_id
WHERE c.case_id = $1
`

type CaseCommentAnchorsRow struct {
	CommentID  string
	StepID     string
	VariantID  string
	AnchorHash *string
}

// The captures each comment covers, with the bytes the remark was written on
// (#132): what decides whether a refusal still talks about the image shown.
func (q *Queries) CaseCommentAnchors(ctx context.Context, caseID string) ([]CaseCommentAnchorsRow, error) {
	rows, err := q.db.Query(ctx, caseCommentAnchors, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseCommentAnchorsRow{}
	for rows.Next() {
		var i CaseCommentAnchorsRow
		if err := rows.Scan(
			&i.CommentID,
			&i.StepID,
			&i.VariantID,
			&i.AnchorHash,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseCommentIssues = `-- name: CaseCommentIssues :many
SELECT ci.id, ci.comment_id, ci.issue_id, ci.url, ci.title, ci.state, ci.created_at, (
    SELECT j.remark FROM comment_judgments j
    WHERE j.comment_issue_id = ci.id AND j.verdict = 'refused'
    ORDER BY j.created_at DESC LIMIT 1
) AS last_refusal
FROM comment_issues ci
JOIN comments c ON c.id = ci.comment_id
WHERE c.case_id = $1
ORDER BY ci.comment_id, ci.created_at
`

type CaseCommentIssuesRow struct {
	ID          string
	CommentID   string
	IssueID     string
	Url         *string
	Title       *string
	State       string
	CreatedAt   pgtype.Timestamptz
	LastRefusal *string
}

// The refs of every comment of one case, with each ref's last refusal remark:
// what the dev has to read is the remark, and the table shows it under the
// title (#138).
func (q *Queries) CaseCommentIssues(ctx context.Context, caseID string) ([]CaseCommentIssuesRow, error) {
	rows, err := q.db.Query(ctx, caseCommentIssues, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseCommentIssuesRow{}
	for rows.Next() {
		var i CaseCommentIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.IssueID,
			&i.Url,
			&i.Title,
			&i.State,
			&i.CreatedAt,
			&i.LastRefusal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseComments = `-- name: CaseComments :many
SELECT c.id, c.step_id, c.body, c.state,
       c.discard_reason, c.author_id, c.created_at, c.updated_at,
       array_remove(array_agg(cv.variant_id), NULL)::text[] AS variant_ids
FROM comments c
LEFT JOIN comment_variants cv ON cv.comment_id = c.id
JOIN cases k ON k.id = c.case_id
WHERE c.case_id = $1 AND k.project_id = $2
GROUP BY c.id
ORDER BY c.created_at
`

type CaseCommentsParams struct {
	CaseID    string
	ProjectID string
}

type CaseCommentsRow struct {
	ID            string
	StepID        string
	Body          string
	State         string
	DiscardReason *string
	AuthorID      string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	VariantIds    []string
}

// Scoped by the project, not merely filtered by the case: a case id from
// another project returns nothing rather than someone else's remarks (#71).
func (q *Queries) CaseComments(ctx context.Context, arg CaseCommentsParams) ([]CaseCommentsRow, error) {
	rows, err := q.db.Query(ctx, caseComments, arg.CaseID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseCommentsRow{}
	for rows.Next() {
		var i CaseCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StepID,
			&i.Body,
			&i.State,
			&i.DiscardReason,
			&i.AuthorID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.VariantIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseReferences = `-- name: CaseReferences :many
SELECT step_id, variant_id, environment_id, blob_hash, approved_by, approved_at
FROM capture_references
WHERE case_id = $1
ORDER BY step_id, variant_id, environment_id
`

type CaseReferencesRow struct {
	StepID        string
	VariantID     string
	EnvironmentID string
	BlobHash      string
	ApprovedBy    string
	ApprovedAt    pgtype.Timestamptz
}

// What a case is judged against right now, and who wrote the reference.
func (q *Queries) CaseReferences(ctx context.Context, caseID string) ([]CaseReferencesRow, error) {
	rows, err := q.db.Query(ctx, caseReferences, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseReferencesRow{}
	for rows.Next() {
		var i CaseReferencesRow
		if err := rows.Scan(
			&i.StepID,
			&i.VariantID,
			&i.EnvironmentID,
			&i.BlobHash,
			&i.ApprovedBy,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const casesWithCaptureCounts = `-- name: CasesWithCaptureCounts :many
WITH latest AS (
    SELECT id FROM editions
    WHERE project_id = $1
    ORDER BY created_at DESC, id DESC
    LIMIT 1
)
SELECT
    k.id, k.project_id, k.category_id, k.title, k.description, k.state, k.archived_at, k.created_at, k.updated_at, k.current_edition_id,
    count(c.id)                                                        AS captures,
    max(e.created_at)::timestamptz                                     AS last_edition
FROM cases k
LEFT JOIN steps s ON s.case_id = k.id
LEFT JOIN captures c ON c.step_id = s.id AND c.edition_id = (SELECT id FROM latest)
LEFT JOIN editions e ON e.id = c.edition_id
WHERE k.project_id = $1
  AND k.archived_at IS NULL
  AND ($2::text IS NULL OR k.category_id = $2::text)
GROUP BY k.id
ORDER BY k.title
`

type CasesWithCaptureCountsParams struct {
	ProjectID  string
	CategoryID *string
}

type CasesWithCaptureCountsRow struct {
	ID               string
	ProjectID        string
	CategoryID       *string
	Title            string
	Description      *string
	State            string
	ArchivedAt       pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	CurrentEditionID *string
	Captures         int64
	LastEdition      pgtype.Timestamptz
}

// Every case with the state of its captures at the edition it points at.
//
// The verdict rows only exist once a reviewer has written something, so a case
// that has captures but no verdict reports them as still to judge.
func (q *Queries) CasesWithCaptureCounts(ctx context.Context, arg CasesWithCaptureCountsParams) ([]CasesWithCaptureCountsRow, error) {
	rows, err := q.db.Query(ctx, casesWithCaptureCounts, arg.ProjectID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CasesWithCaptureCountsRow{}
	for rows.Next() {
		var i CasesWithCaptureCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.State,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentEditionID,
			&i.Captures,
			&i.LastEdition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const categoryTreeWithCounts = `-- name: CategoryTreeWithCounts :many
WITH RECURSIVE descendants AS (
    -- Each category is its own descendant, so a node's own cases count too.
    SELECT id AS root_id, id AS node_id
    FROM categories
    WHERE project_id = $1
  UNION ALL
    SELECT d.root_id, c.id
    FROM categories c
    JOIN descendants d ON c.parent_id = d.node_id
)
SELECT
    cat.id,
    cat.parent_id,
    cat.name,
    cat.position,
    count(k.id)                                                    AS cases,
    count(k.id) FILTER (WHERE k.state = 'not-instrumented')        AS not_instrumented,
    count(k.id) FILTER (WHERE k.state = 'to-review')               AS to_review,
    count(k.id) FILTER (WHERE k.state = 'refused')                 AS refused,
    count(k.id) FILTER (WHERE k.state = 'accepted')                AS accepted,
    max(k.updated_at)::timestamptz                                 AS last_activity
FROM categories cat
LEFT JOIN descendants d ON d.root_id = cat.id
LEFT JOIN cases k ON k.category_id = d.node_id AND k.archived_at IS NULL
WHERE cat.project_id = $1
GROUP BY cat.id, cat.parent_id, cat.name, cat.position
ORDER BY cat.parent_id NULLS FIRST, cat.position, cat.name
`

type CategoryTreeWithCountsRow struct {
	ID              string
	ParentID        *string
	Name            string
	Position        int32
	Cases           int64
	NotInstrumented int64
	ToReview        int64
	Refused         int64
	Accepted        int64
	LastActivity    pgtype.Timestamptz
}

// Every category with the case counts of its whole descendance.
//
// A recursive CTE rather than a walk: a branch in trouble has to be visible
// from the root, and drawing one bar must not cost one query per node.
func (q *Queries) CategoryTreeWithCounts(ctx context.Context, projectID string) ([]CategoryTreeWithCountsRow, error) {
	rows, err := q.db.Query(ctx, categoryTreeWithCounts, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CategoryTreeWithCountsRow{}
	for rows.Next() {
		var i CategoryTreeWithCountsRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Name,
			&i.Position,
			&i.Cases,
			&i.NotInstrumented,
			&i.ToReview,
			&i.Refused,
			&i.Accepted,
			&i.LastActivity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentCoveredVariants = `-- name: CommentCoveredVariants :many
SELECT variant_id FROM comment_variants WHERE comment_id = $1
`

func (q *Queries) CommentCoveredVariants(ctx context.Context, commentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, commentCoveredVariants, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var variant_id string
		if err := rows.Scan(&variant_id); err != nil {
			return nil, err
		}
		items = append(items, variant_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentIssueStates = `-- name: CommentIssueStates :many
SELECT state FROM comment_issues WHERE comment_id = $1
`

func (q *Queries) CommentIssueStates(ctx context.Context, commentID string) ([]string, error) {
	rows, err := q.db.Query(ctx, commentIssueStates, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var state string
		if err := rows.Scan(&state); err != nil {
			return nil, err
		}
		items = append(items, state)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const commentJudgments = `-- name: CommentJudgments :many
SELECT id, comment_id, verdict, remark, actor_id, created_at, comment_issue_id FROM comment_judgments WHERE comment_id = $1 ORDER BY created_at
`

func (q *Queries) CommentJudgments(ctx context.Context, commentID string) ([]CommentJudgment, error) {
	rows, err := q.db.Query(ctx, commentJudgments, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentJudgment{}
	for rows.Next() {
		var i CommentJudgment
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.Verdict,
			&i.Remark,
			&i.ActorID,
			&i.CreatedAt,
			&i.CommentIssueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createComment = `-- name: CreateComment :one
INSERT INTO comments (case_id, step_id, body, author_id)
VALUES ($1, $2, $3, $4)
RETURNING id, case_id, step_id, body, state, discard_reason, author_id, created_at, updated_at
`

type CreateCommentParams struct {
	CaseID   string
	StepID   string
	Body     string
	AuthorID string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.CaseID,
		arg.StepID,
		arg.Body,
		arg.AuthorID,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.StepID,
		&i.Body,
		&i.State,
		&i.DiscardReason,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createCommentIssue = `-- name: CreateCommentIssue :one
INSERT INTO comment_issues (comment_id, issue_id, url, title)
VALUES ($1, $2, $3, $4)
RETURNING id, comment_id, issue_id, url, title, state, created_at
`

type CreateCommentIssueParams struct {
	CommentID string
	IssueID   string
	Url       *string
	Title     *string
}

// One row per attached issue; attaching twice adds a second (#138).
func (q *Queries) CreateCommentIssue(ctx context.Context, arg CreateCommentIssueParams) (CommentIssue, error) {
	row := q.db.QueryRow(ctx, createCommentIssue,
		arg.CommentID,
		arg.IssueID,
		arg.Url,
		arg.Title,
	)
	var i CommentIssue
	err := row.Scan(
		&i.ID,
		&i.CommentID,
		&i.IssueID,
		&i.Url,
		&i.Title,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCaptureAcceptance = `-- name: DeleteCaptureAcceptance :exec
DELETE FROM capture_acceptances
WHERE case_id = $1 AND step_id = $2 AND variant_id = $3
`

type DeleteCaptureAcceptanceParams struct {
	CaseID    string
	StepID    string
	VariantID string
}

// Taking an acceptance back deletes the row rather than writing a state: the
// recompute below re-derives the capture from what remains, and the journal is
// what remembers both moves (#156).
func (q *Queries) DeleteCaptureAcceptance(ctx context.Context, arg DeleteCaptureAcceptanceParams) error {
	_, err := q.db.Exec(ctx, deleteCaptureAcceptance, arg.CaseID, arg.StepID, arg.VariantID)
	return err
}

const deleteComment = `-- name: DeleteComment :exec
DELETE FROM comments WHERE id = $1
`

func (q *Queries) DeleteComment(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const detachCommentVariants = `-- name: DetachCommentVariants :exec
DELETE FROM comment_variants WHERE comment_id = $1
`

func (q *Queries) DetachCommentVariants(ctx context.Context, commentID string) error {
	_, err := q.db.Exec(ctx, detachCommentVariants, commentID)
	return err
}

const discardComment = `-- name: DiscardComment :exec
UPDATE comments SET state = $2, discard_reason = $3, updated_at = now() WHERE id = $1
`

type DiscardCommentParams struct {
	ID            string
	State         string
	DiscardReason *string
}

func (q *Queries) DiscardComment(ctx context.Context, arg DiscardCommentParams) error {
	_, err := q.db.Exec(ctx, discardComment, arg.ID, arg.State, arg.DiscardReason)
	return err
}

const draftCommentsOnCapture = `-- name: DraftCommentsOnCapture :many
SELECT DISTINCT c.id FROM comments c
JOIN comment_variants cv ON cv.comment_id = c.id
WHERE c.case_id = $1 AND c.step_id = $2 AND cv.variant_id = $3
  AND c.author_id = $4 AND c.state = 'to-track'
  AND NOT EXISTS (SELECT 1 FROM comment_issues ci WHERE ci.comment_id = c.id)
`

type DraftCommentsOnCaptureParams struct {
	CaseID    string
	StepID    string
	VariantID string
	AuthorID  string
}

// The reviewer's own drafts on one capture: remarks with no issue attached yet.
// Withdrawing a draft refusal takes them with it — ADR 0020's explicit
// exception to "nothing is deleted", scoped to the author's own drafts.
func (q *Queries) DraftCommentsOnCapture(ctx context.Context, arg DraftCommentsOnCaptureParams) ([]string, error) {
	rows, err := q.db.Query(ctx, draftCommentsOnCapture,
		arg.CaseID,
		arg.StepID,
		arg.VariantID,
		arg.AuthorID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getComment = `-- name: GetComment :one
SELECT c.id, c.case_id, c.step_id, c.body, c.state, c.discard_reason, c.author_id, c.created_at, c.updated_at FROM comments c
JOIN cases k ON k.id = c.case_id
JOIN projects p ON p.id = k.project_id
WHERE c.id = $1 AND p.slug = $2
`

type GetCommentParams struct {
	ID   string
	Slug string
}

// A comment, inside the project the caller named. Reached through its case,
// which is what carries the project: the comment table names no project of its
// own (#71).
func (q *Queries) GetComment(ctx context.Context, arg GetCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, getComment, arg.ID, arg.Slug)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.StepID,
		&i.Body,
		&i.State,
		&i.DiscardReason,
		&i.AuthorID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCommentIssue = `-- name: GetCommentIssue :many
SELECT ci.id, ci.comment_id, ci.issue_id, ci.url, ci.title, ci.state, ci.created_at FROM comment_issues ci
JOIN comments c ON c.id = ci.comment_id
JOIN cases k ON k.id = c.case_id
JOIN projects p ON p.id = k.project_id
WHERE ci.comment_id = $1 AND p.slug = $2
  AND ($3::text = '' OR ci.id = $3)
ORDER BY ci.created_at
LIMIT 2
`

type GetCommentIssueParams struct {
	CommentID string
	Slug      string
	Column3   string
}

// Scoped through the comment and its project, like the comment itself (#71).
func (q *Queries) GetCommentIssue(ctx context.Context, arg GetCommentIssueParams) ([]CommentIssue, error) {
	rows, err := q.db.Query(ctx, getCommentIssue, arg.CommentID, arg.Slug, arg.Column3)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommentIssue{}
	for rows.Next() {
		var i CommentIssue
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.IssueID,
			&i.Url,
			&i.Title,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordCaptureAcceptance = `-- name: RecordCaptureAcceptance :exec
INSERT INTO capture_acceptances (case_id, step_id, variant_id, accepted_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (case_id, step_id, variant_id) DO NOTHING
`

type RecordCaptureAcceptanceParams struct {
	CaseID     string
	StepID     string
	VariantID  string
	AcceptedBy *string
}

// The acceptance is the reviewer's own fact — who, and when (ADR 0021).
// Recording it is the write; every status is derived at read time.
// The old note stands for the case state: recorded, never set by a caller: recording a
// comment and recomputing what it covers happen together (ADR 0012).
func (q *Queries) RecordCaptureAcceptance(ctx context.Context, arg RecordCaptureAcceptanceParams) error {
	_, err := q.db.Exec(ctx, recordCaptureAcceptance,
		arg.CaseID,
		arg.StepID,
		arg.VariantID,
		arg.AcceptedBy,
	)
	return err
}

const recordJudgment = `-- name: RecordJudgment :exec
INSERT INTO comment_judgments (comment_id, comment_issue_id, verdict, remark, actor_id)
VALUES ($1, $2, $3, $4, $5)
`

type RecordJudgmentParams struct {
	CommentID      string
	CommentIssueID *string
	Verdict        string
	Remark         *string
	ActorID        string
}

// Every judgment is kept: three round trips on one comment is information
// (ADR 0012).
func (q *Queries) RecordJudgment(ctx context.Context, arg RecordJudgmentParams) error {
	_, err := q.db.Exec(ctx, recordJudgment,
		arg.CommentID,
		arg.CommentIssueID,
		arg.Verdict,
		arg.Remark,
		arg.ActorID,
	)
	return err
}

const releaseToLatestEdition = `-- name: ReleaseToLatestEdition :exec
UPDATE cases k
SET current_edition_id = (
        SELECT e.id FROM editions e
        WHERE e.project_id = k.project_id
        ORDER BY e.created_at DESC, e.id DESC
        LIMIT 1
    ),
    updated_at = now()
WHERE k.id = $1
`

// A review that ends releases the case onto the project's most recent edition:
// it was only held back so the reviewer judged one fixed set of bytes.
func (q *Queries) ReleaseToLatestEdition(ctx context.Context, caseID string) error {
	_, err := q.db.Exec(ctx, releaseToLatestEdition, caseID)
	return err
}

const setCaseState = `-- name: SetCaseState :exec
UPDATE cases SET state = $2, updated_at = now() WHERE id = $1
`

type SetCaseStateParams struct {
	ID    string
	State string
}

func (q *Queries) SetCaseState(ctx context.Context, arg SetCaseStateParams) error {
	_, err := q.db.Exec(ctx, setCaseState, arg.ID, arg.State)
	return err
}

const setCommentIssueState = `-- name: SetCommentIssueState :exec
UPDATE comment_issues SET state = $2 WHERE id = $1
`

type SetCommentIssueStateParams struct {
	ID    string
	State string
}

func (q *Queries) SetCommentIssueState(ctx context.Context, arg SetCommentIssueStateParams) error {
	_, err := q.db.Exec(ctx, setCommentIssueState, arg.ID, arg.State)
	return err
}

const setCommentState = `-- name: SetCommentState :exec
UPDATE comments SET state = $2, updated_at = now() WHERE id = $1
`

type SetCommentStateParams struct {
	ID    string
	State string
}

// The state is written by the server as a consequence of a recorded move,
// never received as an argument (ADR 0002).
func (q *Queries) SetCommentState(ctx context.Context, arg SetCommentStateParams) error {
	_, err := q.db.Exec(ctx, setCommentState, arg.ID, arg.State)
	return err
}

const settledRefsOnCapture = `-- name: SettledRefsOnCapture :many
SELECT ci.id, ci.comment_id, ci.state, c.state AS comment_state
FROM comment_issues ci
JOIN comments c ON c.id = ci.comment_id
JOIN comment_variants cv ON cv.comment_id = c.id
WHERE c.case_id = $1 AND c.step_id = $2 AND cv.variant_id = $3
  AND c.state = 'accepted' AND ci.state = 'accepted'
`

type SettledRefsOnCaptureParams struct {
	CaseID    string
	StepID    string
	VariantID string
}

type SettledRefsOnCaptureRow struct {
	ID           string
	CommentID    string
	State        string
	CommentState string
}

// The accepted refs whose settling made one capture read accepted: the ones
// an unvalidate on that capture must take back (#167). A discarded comment
// keeps its refs untouched — discarding was said with a reason and it stands.
func (q *Queries) SettledRefsOnCapture(ctx context.Context, arg SettledRefsOnCaptureParams) ([]SettledRefsOnCaptureRow, error) {
	rows, err := q.db.Query(ctx, settledRefsOnCapture, arg.CaseID, arg.StepID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettledRefsOnCaptureRow{}
	for rows.Next() {
		var i SettledRefsOnCaptureRow
		if err := rows.Scan(
			&i.ID,
			&i.CommentID,
			&i.State,
			&i.CommentState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const settledRemarksOnCapture = `-- name: SettledRemarksOnCapture :many
SELECT c.id, c.state FROM comments c
JOIN comment_variants cv ON cv.comment_id = c.id
WHERE c.case_id = $1 AND c.step_id = $2 AND cv.variant_id = $3
  AND c.state = 'accepted'
  AND NOT EXISTS (SELECT 1 FROM comment_issues ci WHERE ci.comment_id = c.id)
`

type SettledRemarksOnCaptureParams struct {
	CaseID    string
	StepID    string
	VariantID string
}

type SettledRemarksOnCaptureRow struct {
	ID    string
	State string
}

// The settled ref-less remarks whose acceptance made one capture read
// accepted: unaccepting that capture takes their judgment back too (#167,
// #175) — the rule is "whatever made it accepted", refs and remarks alike.
func (q *Queries) SettledRemarksOnCapture(ctx context.Context, arg SettledRemarksOnCaptureParams) ([]SettledRemarksOnCaptureRow, error) {
	rows, err := q.db.Query(ctx, settledRemarksOnCapture, arg.CaseID, arg.StepID, arg.VariantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SettledRemarksOnCaptureRow{}
	for rows.Next() {
		var i SettledRemarksOnCaptureRow
		if err := rows.Scan(&i.ID, &i.State); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stampCaptureReference = `-- name: StampCaptureReference :exec
INSERT INTO capture_references (case_id, step_id, variant_id, environment_id, blob_hash, approved_by)
SELECT
    $1, c.step_id, c.variant_id,
    coalesce(c.provenance->>'environmentId', ''),
    c.blob_hash, $2
FROM captures c
WHERE c.edition_id = $3
  AND c.step_id = $4
  AND c.variant_id = $5
ON CONFLICT (case_id, step_id, variant_id, environment_id) DO UPDATE
SET blob_hash   = EXCLUDED.blob_hash,
    approved_by = EXCLUDED.approved_by,
    approved_at = now()
`

type StampCaptureReferenceParams struct {
	CaseID     string
	ApprovedBy string
	EditionID  string
	StepID     string
	VariantID  string
}

// The bytes a reviewer approved, taken from the edition they were judging.
//
// Nothing is stamped when that edition holds no capture for the step and variant: a
// validated hole approves nothing. The environment comes from the capture's own
// provenance, so a reference never crosses environments (ADR 0004, ADR 0017).
func (q *Queries) StampCaptureReference(ctx context.Context, arg StampCaptureReferenceParams) error {
	_, err := q.db.Exec(ctx, stampCaptureReference,
		arg.CaseID,
		arg.ApprovedBy,
		arg.EditionID,
		arg.StepID,
		arg.VariantID,
	)
	return err
}

const updateCommentBody = `-- name: UpdateCommentBody :exec
UPDATE comments SET body = $2, updated_at = now() WHERE id = $1
`

type UpdateCommentBodyParams struct {
	ID   string
	Body string
}

// Editing is the author reworking their own draft (ADR 0020): body only —
// variants are replaced beside it in the same transaction.
func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) error {
	_, err := q.db.Exec(ctx, updateCommentBody, arg.ID, arg.Body)
	return err
}
