// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package sqlcgen

import (
	"context"
)

const captureBlobInProject = `-- name: CaptureBlobInProject :one
SELECT c.blob_hash FROM captures c
JOIN steps st ON st.id = c.step_id
JOIN cases k ON k.id = st.case_id
JOIN projects p ON p.id = k.project_id
WHERE c.id = $1 AND p.slug = $2
`

type CaptureBlobInProjectParams struct {
	ID   string
	Slug string
}

// The bytes one capture holds, inside the project the caller named. Reached
// through the capture's own row, because a content address names no project
// and cannot be authorised (product.md §8.1).
func (q *Queries) CaptureBlobInProject(ctx context.Context, arg CaptureBlobInProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, captureBlobInProject, arg.ID, arg.Slug)
	var blob_hash string
	err := row.Scan(&blob_hash)
	return blob_hash, err
}

const caseEvidence = `-- name: CaseEvidence :many
SELECT
    s.id       AS step_id,
    s.name     AS step_name,
    s.position AS step_position,
    v.id       AS variant_id,
    v.label    AS variant_label,
    v.values   AS variant_values,
    c.id       AS capture_id,
    c.blob_hash,
    c.provenance,
    c.moved_pixels
FROM steps s
JOIN captures c ON c.step_id = s.id AND c.edition_id = $2
JOIN variants v ON v.id = c.variant_id
WHERE s.case_id = $1
ORDER BY s.position, v.label
`

type CaseEvidenceParams struct {
	CaseID    string
	EditionID string
}

type CaseEvidenceRow struct {
	StepID        string
	StepName      string
	StepPosition  int32
	VariantID     string
	VariantLabel  string
	VariantValues []byte
	CaptureID     string
	BlobHash      string
	Provenance    []byte
	MovedPixels   *int32
}

// Every capture of one case at one edition, joined with its step and variant.
// One query rather than a walk over steps: a case with thirty steps in eight
// variants would otherwise be two hundred and forty round trips.
// A step belongs to the view only if the displayed edition captured it: since
// steps outlive editions (#135), one born in a later edition would otherwise
// render in an older view as a row of `missing` marks — and `missing` means a
// failed run (ADR 0016), not a screen from the future (#137).
func (q *Queries) CaseEvidence(ctx context.Context, arg CaseEvidenceParams) ([]CaseEvidenceRow, error) {
	rows, err := q.db.Query(ctx, caseEvidence, arg.CaseID, arg.EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseEvidenceRow{}
	for rows.Next() {
		var i CaseEvidenceRow
		if err := rows.Scan(
			&i.StepID,
			&i.StepName,
			&i.StepPosition,
			&i.VariantID,
			&i.VariantLabel,
			&i.VariantValues,
			&i.CaptureID,
			&i.BlobHash,
			&i.Provenance,
			&i.MovedPixels,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const caseRecordings = `-- name: CaseRecordings :many
SELECT r.id AS recording_id, r.blob_hash, v.id AS variant_id, v.label AS variant_label, v.values AS variant_values
FROM recordings r
JOIN variants v ON v.id = r.variant_id
WHERE r.case_id = $1 AND r.edition_id = $2
ORDER BY v.label
`

type CaseRecordingsParams struct {
	CaseID    string
	EditionID string
}

type CaseRecordingsRow struct {
	RecordingID   string
	BlobHash      string
	VariantID     string
	VariantLabel  string
	VariantValues []byte
}

func (q *Queries) CaseRecordings(ctx context.Context, arg CaseRecordingsParams) ([]CaseRecordingsRow, error) {
	rows, err := q.db.Query(ctx, caseRecordings, arg.CaseID, arg.EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CaseRecordingsRow{}
	for rows.Next() {
		var i CaseRecordingsRow
		if err := rows.Scan(
			&i.RecordingID,
			&i.BlobHash,
			&i.VariantID,
			&i.VariantLabel,
			&i.VariantValues,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const editionByID = `-- name: EditionByID :one
SELECT id, project_id, revision, created_at FROM editions WHERE id = $1 AND project_id = $2
`

type EditionByIDParams struct {
	ID        string
	ProjectID string
}

func (q *Queries) EditionByID(ctx context.Context, arg EditionByIDParams) (Edition, error) {
	row := q.db.QueryRow(ctx, editionByID, arg.ID, arg.ProjectID)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecordingJudgment = `-- name: InsertRecordingJudgment :exec
INSERT INTO recording_judgments (recording_id, verdict, remark, actor_id)
VALUES ($1, $2, $3, $4)
`

type InsertRecordingJudgmentParams struct {
	RecordingID string
	Verdict     string
	Remark      *string
	ActorID     string
}

// A recording's standing comes from its last judgment (ADR 0023): none or a
// take-back reads to-review, and a refusal keeps its remark for the dev.
func (q *Queries) InsertRecordingJudgment(ctx context.Context, arg InsertRecordingJudgmentParams) error {
	_, err := q.db.Exec(ctx, insertRecordingJudgment,
		arg.RecordingID,
		arg.Verdict,
		arg.Remark,
		arg.ActorID,
	)
	return err
}

const lastRecordingJudgments = `-- name: LastRecordingJudgments :many
SELECT r.id AS recording_id, j.verdict, j.remark
FROM recordings r
JOIN LATERAL (
    SELECT verdict, remark FROM recording_judgments
    WHERE recording_id = r.id
    ORDER BY created_at DESC LIMIT 1
) j ON true
WHERE r.case_id = $1 AND r.edition_id = $2
`

type LastRecordingJudgmentsParams struct {
	CaseID    string
	EditionID string
}

type LastRecordingJudgmentsRow struct {
	RecordingID string
	Verdict     string
	Remark      *string
}

func (q *Queries) LastRecordingJudgments(ctx context.Context, arg LastRecordingJudgmentsParams) ([]LastRecordingJudgmentsRow, error) {
	rows, err := q.db.Query(ctx, lastRecordingJudgments, arg.CaseID, arg.EditionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LastRecordingJudgmentsRow{}
	for rows.Next() {
		var i LastRecordingJudgmentsRow
		if err := rows.Scan(&i.RecordingID, &i.Verdict, &i.Remark); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestEdition = `-- name: LatestEdition :one
SELECT id, project_id, revision, created_at FROM editions
WHERE project_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

// The edition a case is read against defaults to the project's most recent.
func (q *Queries) LatestEdition(ctx context.Context, projectID string) (Edition, error) {
	row := q.db.QueryRow(ctx, latestEdition, projectID)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const recordingBlobInProject = `-- name: RecordingBlobInProject :one
SELECT r.blob_hash FROM recordings r
JOIN cases k ON k.id = r.case_id
JOIN projects p ON p.id = k.project_id
WHERE r.id = $1 AND p.slug = $2
`

type RecordingBlobInProjectParams struct {
	ID   string
	Slug string
}

func (q *Queries) RecordingBlobInProject(ctx context.Context, arg RecordingBlobInProjectParams) (string, error) {
	row := q.db.QueryRow(ctx, recordingBlobInProject, arg.ID, arg.Slug)
	var blob_hash string
	err := row.Scan(&blob_hash)
	return blob_hash, err
}

const recordingInProject = `-- name: RecordingInProject :one
SELECT r.id, r.case_id FROM recordings r
JOIN cases k ON k.id = r.case_id
JOIN projects p ON p.id = k.project_id
WHERE r.id = $1 AND p.slug = $2
`

type RecordingInProjectParams struct {
	ID   string
	Slug string
}

type RecordingInProjectRow struct {
	ID     string
	CaseID string
}

// The recording inside the project the caller named, with its case: what a
// judgment needs to authorise and to recompute.
func (q *Queries) RecordingInProject(ctx context.Context, arg RecordingInProjectParams) (RecordingInProjectRow, error) {
	row := q.db.QueryRow(ctx, recordingInProject, arg.ID, arg.Slug)
	var i RecordingInProjectRow
	err := row.Scan(&i.ID, &i.CaseID)
	return i, err
}
