// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: intake.sql

package sqlcgen

import (
	"context"
)

const advanceCurrentEdition = `-- name: AdvanceCurrentEdition :many
UPDATE cases
SET current_edition_id = $1, updated_at = now()
WHERE id = ANY($2::text[])
  AND (current_edition_id IS NULL OR state <> 'to-review')
RETURNING id
`

type AdvanceCurrentEditionParams struct {
	EditionID *string
	CaseIds   []string
}

// A new edition does not yank the ground from under a reviewer: a case sitting
// at `to-review` keeps pointing at what its reviewer is judging, and advances
// once that review ends (product.md §7). A case that points nowhere always
// advances -- there was nothing to protect.
func (q *Queries) AdvanceCurrentEdition(ctx context.Context, arg AdvanceCurrentEditionParams) ([]string, error) {
	rows, err := q.db.Query(ctx, advanceCurrentEdition, arg.EditionID, arg.CaseIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const blobExists = `-- name: BlobExists :one
SELECT EXISTS (SELECT 1 FROM blobs WHERE hash = $1)
`

func (q *Queries) BlobExists(ctx context.Context, hash string) (bool, error) {
	row := q.db.QueryRow(ctx, blobExists, hash)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const casesByIDs = `-- name: CasesByIDs :many
SELECT id, project_id, category_id, title, description, state, archived_at, created_at, updated_at, current_edition_id FROM cases WHERE project_id = $1 AND id = ANY($2::text[])
`

type CasesByIDsParams struct {
	ProjectID string
	Column2   []string
}

func (q *Queries) CasesByIDs(ctx context.Context, arg CasesByIDsParams) ([]Case, error) {
	rows, err := q.db.Query(ctx, casesByIDs, arg.ProjectID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Case{}
	for rows.Next() {
		var i Case
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.CategoryID,
			&i.Title,
			&i.Description,
			&i.State,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CurrentEditionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countCasesToReview = `-- name: CountCasesToReview :one
SELECT count(*) FROM cases
WHERE project_id = $1 AND archived_at IS NULL AND state = 'to-review'
`

func (q *Queries) CountCasesToReview(ctx context.Context, projectID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCasesToReview, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCapture = `-- name: CreateCapture :one
INSERT INTO captures (edition_id, step_id, variant_id, blob_hash, provenance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, edition_id, step_id, variant_id, blob_hash, provenance
`

type CreateCaptureParams struct {
	EditionID  string
	StepID     string
	VariantID  string
	BlobHash   string
	Provenance []byte
}

func (q *Queries) CreateCapture(ctx context.Context, arg CreateCaptureParams) (Capture, error) {
	row := q.db.QueryRow(ctx, createCapture,
		arg.EditionID,
		arg.StepID,
		arg.VariantID,
		arg.BlobHash,
		arg.Provenance,
	)
	var i Capture
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.StepID,
		&i.VariantID,
		&i.BlobHash,
		&i.Provenance,
	)
	return i, err
}

const createEdition = `-- name: CreateEdition :one
INSERT INTO editions (project_id, revision)
VALUES ($1, $2)
RETURNING id, project_id, revision, created_at
`

type CreateEditionParams struct {
	ProjectID string
	Revision  *string
}

func (q *Queries) CreateEdition(ctx context.Context, arg CreateEditionParams) (Edition, error) {
	row := q.db.QueryRow(ctx, createEdition, arg.ProjectID, arg.Revision)
	var i Edition
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Revision,
		&i.CreatedAt,
	)
	return i, err
}

const createRecording = `-- name: CreateRecording :one
INSERT INTO recordings (edition_id, case_id, variant_id, blob_hash)
VALUES ($1, $2, $3, $4)
RETURNING id, edition_id, case_id, variant_id, blob_hash
`

type CreateRecordingParams struct {
	EditionID string
	CaseID    string
	VariantID string
	BlobHash  string
}

func (q *Queries) CreateRecording(ctx context.Context, arg CreateRecordingParams) (Recording, error) {
	row := q.db.QueryRow(ctx, createRecording,
		arg.EditionID,
		arg.CaseID,
		arg.VariantID,
		arg.BlobHash,
	)
	var i Recording
	err := row.Scan(
		&i.ID,
		&i.EditionID,
		&i.CaseID,
		&i.VariantID,
		&i.BlobHash,
	)
	return i, err
}

const deleteStepsBeyond = `-- name: DeleteStepsBeyond :exec
DELETE FROM steps WHERE case_id = $1 AND position >= $2
`

type DeleteStepsBeyondParams struct {
	CaseID   string
	Position int32
}

func (q *Queries) DeleteStepsBeyond(ctx context.Context, arg DeleteStepsBeyondParams) error {
	_, err := q.db.Exec(ctx, deleteStepsBeyond, arg.CaseID, arg.Position)
	return err
}

const enterReviewOnFirstCaptures = `-- name: EnterReviewOnFirstCaptures :many
UPDATE cases k
SET state = 'to-review', updated_at = now()
WHERE k.id = ANY($1::text[])
  AND k.state = 'not-instrumented'
  AND EXISTS (
      SELECT 1 FROM steps s
      JOIN captures c ON c.step_id = s.id
      WHERE s.case_id = k.id
  )
RETURNING k.id
`

// A case that has just received its first captures leaves the funnel's edge:
// it is no longer uninstrumented, and nobody has judged it yet (ADR 0012).
//
// Only that transition is made here. Every other one is driven by a comment,
// and comments are not part of intake.
func (q *Queries) EnterReviewOnFirstCaptures(ctx context.Context, dollar_1 []string) ([]string, error) {
	rows, err := q.db.Query(ctx, enterReviewOnFirstCaptures, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAxes = `-- name: ListAxes :many
SELECT id, project_id, name, position FROM axes WHERE project_id = $1 ORDER BY position, name
`

func (q *Queries) ListAxes(ctx context.Context, projectID string) ([]Axis, error) {
	rows, err := q.db.Query(ctx, listAxes, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Axis{}
	for rows.Next() {
		var i Axis
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariants = `-- name: ListVariants :many
SELECT id, project_id, values, label FROM variants WHERE project_id = $1
`

// Labels are a rendering of the values, never an identity, so they can be
// rewritten when the order changes.
func (q *Queries) ListVariants(ctx context.Context, projectID string) ([]Variant, error) {
	rows, err := q.db.Query(ctx, listVariants, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Variant{}
	for rows.Next() {
		var i Variant
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Values,
			&i.Label,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordTransition = `-- name: RecordTransition :exec
INSERT INTO journal (project_id, case_id, from_state, to_state, cause, actor_id, actor_kind, inputs, rule_version)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type RecordTransitionParams struct {
	ProjectID   string
	CaseID      *string
	FromState   *string
	ToState     *string
	Cause       string
	ActorID     string
	ActorKind   string
	Inputs      []byte
	RuleVersion int32
}

// Every transition is journalled: without the trace, a stored state cannot
// serve as a regression oracle (ADR 0002).
func (q *Queries) RecordTransition(ctx context.Context, arg RecordTransitionParams) error {
	_, err := q.db.Exec(ctx, recordTransition,
		arg.ProjectID,
		arg.CaseID,
		arg.FromState,
		arg.ToState,
		arg.Cause,
		arg.ActorID,
		arg.ActorKind,
		arg.Inputs,
		arg.RuleVersion,
	)
	return err
}

const relabelVariant = `-- name: RelabelVariant :exec
UPDATE variants SET label = $2 WHERE id = $1
`

type RelabelVariantParams struct {
	ID    string
	Label string
}

func (q *Queries) RelabelVariant(ctx context.Context, arg RelabelVariantParams) error {
	_, err := q.db.Exec(ctx, relabelVariant, arg.ID, arg.Label)
	return err
}

const setAxisPosition = `-- name: SetAxisPosition :exec
UPDATE axes SET position = $3 WHERE project_id = $1 AND name = $2
`

type SetAxisPositionParams struct {
	ProjectID string
	Name      string
	Position  int32
}

func (q *Queries) SetAxisPosition(ctx context.Context, arg SetAxisPositionParams) error {
	_, err := q.db.Exec(ctx, setAxisPosition, arg.ProjectID, arg.Name, arg.Position)
	return err
}

const upsertAxis = `-- name: UpsertAxis :one
INSERT INTO axes (project_id, name, position)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, name) DO UPDATE SET name = EXCLUDED.name
RETURNING id, project_id, name, position
`

type UpsertAxisParams struct {
	ProjectID string
	Name      string
	Position  int32
}

// Axes are declared by the project, and created on the fly the first time a
// capture mentions one: ozalid ships no built-in list (ADR 0001).
func (q *Queries) UpsertAxis(ctx context.Context, arg UpsertAxisParams) (Axis, error) {
	row := q.db.QueryRow(ctx, upsertAxis, arg.ProjectID, arg.Name, arg.Position)
	var i Axis
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const upsertBlob = `-- name: UpsertBlob :exec
INSERT INTO blobs (hash, size_bytes)
VALUES ($1, $2)
ON CONFLICT (hash) DO NOTHING
`

type UpsertBlobParams struct {
	Hash      string
	SizeBytes int64
}

func (q *Queries) UpsertBlob(ctx context.Context, arg UpsertBlobParams) error {
	_, err := q.db.Exec(ctx, upsertBlob, arg.Hash, arg.SizeBytes)
	return err
}

const upsertStep = `-- name: UpsertStep :one
INSERT INTO steps (case_id, name, position)
VALUES ($1, $2, $3)
ON CONFLICT (case_id, position) DO UPDATE SET name = EXCLUDED.name
RETURNING id, case_id, name, position
`

type UpsertStepParams struct {
	CaseID   string
	Name     string
	Position int32
}

// Steps are reconciled per case: the manifest gives the order, and re-pushing
// the same step keeps its identity so the comments anchored to it survive.
func (q *Queries) UpsertStep(ctx context.Context, arg UpsertStepParams) (Step, error) {
	row := q.db.QueryRow(ctx, upsertStep, arg.CaseID, arg.Name, arg.Position)
	var i Step
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.Name,
		&i.Position,
	)
	return i, err
}

const upsertVariant = `-- name: UpsertVariant :one
INSERT INTO variants (project_id, values, label)
VALUES ($1, $2, $3)
ON CONFLICT (project_id, values) DO UPDATE SET label = EXCLUDED.label
RETURNING id, project_id, values, label
`

type UpsertVariantParams struct {
	ProjectID string
	Values    []byte
	Label     string
}

// A variant is a combination of axis values, held canonically so an axis the
// client did not supply is absent rather than null.
func (q *Queries) UpsertVariant(ctx context.Context, arg UpsertVariantParams) (Variant, error) {
	row := q.db.QueryRow(ctx, upsertVariant, arg.ProjectID, arg.Values, arg.Label)
	var i Variant
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Values,
		&i.Label,
	)
	return i, err
}
