// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Axis struct {
	ID        string
	ProjectID string
	Name      string
	Position  int32
}

type Blob struct {
	Hash      string
	SizeBytes int64
	CreatedAt pgtype.Timestamptz
}

type Capture struct {
	ID         string
	EditionID  string
	StepID     string
	VariantID  string
	BlobHash   string
	Provenance []byte
}

type CaptureReference struct {
	CaseID     string
	StepID     string
	VariantID  string
	BlobHash   string
	ApprovedBy string
	ApprovedAt pgtype.Timestamptz
}

type CaptureVerdict struct {
	CaseID    string
	StepID    string
	VariantID string
	Status    string
	UpdatedAt pgtype.Timestamptz
}

type Case struct {
	ID          string
	ProjectID   string
	CategoryID  *string
	Title       string
	Description *string
	State       string
	ArchivedAt  pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type Category struct {
	ID        string
	ProjectID string
	ParentID  *string
	Name      string
	Position  int32
	CreatedAt pgtype.Timestamptz
}

type Comment struct {
	ID            string
	CaseID        string
	StepID        string
	Kind          string
	Body          string
	State         string
	IssueRef      *string
	IssueUrl      *string
	IssueTitle    *string
	DiscardReason *string
	AuthorID      string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type CommentJudgment struct {
	ID        string
	CommentID string
	Verdict   string
	Remark    *string
	ActorID   string
	CreatedAt pgtype.Timestamptz
}

type CommentVariant struct {
	CommentID string
	VariantID string
}

type Edition struct {
	ID        string
	ProjectID string
	Revision  *string
	CreatedAt pgtype.Timestamptz
}

type Journal struct {
	ID          int64
	ProjectID   string
	CaseID      *string
	FromState   *string
	ToState     *string
	Cause       string
	ActorID     string
	ActorKind   string
	Inputs      []byte
	RuleVersion int32
	At          pgtype.Timestamptz
}

type Project struct {
	ID           string
	Slug         string
	Name         string
	IntakePolicy string
	CreatedAt    pgtype.Timestamptz
}

type Recording struct {
	ID        string
	EditionID string
	CaseID    string
	VariantID string
	BlobHash  string
}

type Step struct {
	ID       string
	CaseID   string
	Name     string
	Position int32
}

type Variant struct {
	ID        string
	ProjectID string
	Values    []byte
	Label     string
}
