/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the service is able to serve */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a sign-in link
         * @description Sends a link to the address, good once and for a few minutes.
         *
         *     **The answer is the same whether the address is known or not.** Whether
         *     somebody has an account here is not something a stranger gets to learn by
         *     asking.
         */
        post: operations["requestSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-in/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Spend a sign-in link and open a session
         * @description The session is set as an `HttpOnly` cookie, so no script can read it.
         *
         *     Expired, already spent and never issued are one answer: the browser is told
         *     the link no longer works, and learns nothing about which of the three it
         *     was.
         */
        post: operations["claimSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sign-out": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * End this session
         * @description This browser's session, and no other. Signing out here does not sign out
         *     elsewhere.
         */
        post: operations["signOut"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who this request resolves to
         * @description What the client needs to know whether to show a review or a sign-in form.
         */
        get: operations["whoAmI"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/blobs/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Store content under its address
         * @description Idempotent: storing content that is already held changes nothing. The bytes
         *     are refused if they do not produce the announced address — content sitting
         *     at an address that does not describe it would hand every future reader the
         *     wrong evidence with no way to notice.
         *
         *     When the address is already held the upload is answered `204` without the
         *     body being read at all, so a client sending the wrong bytes under a known
         *     address is not told. The stored content is still correct; verifying would
         *     mean reading every upload in full, which is the cost this avoids. Call
         *     `HEAD` first and skip what is already held.
         */
        put: operations["putBlob"];
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Report whether the store already holds this content
         * @description Intake calls this before sending bytes: content already held is never
         *     uploaded again, which is what makes a full visual history affordable.
         *
         *     Answered for the project the caller is pushing to. The store itself is
         *     shared across projects — identical bytes are held once
         *     ([ADR 0004](https://github.com/haribo/ozalid/blob/develop/docs/adr/0004-content-addressed-capture-storage.md)) —
         *     so this says what intake needs to know and nothing about who else holds it.
         */
        head: operations["headBlob"];
        patch?: never;
        trace?: never;
    };
    "/accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every account on this instance
         * @description Deactivated accounts are listed too, and say so. They are what a name in the
         *     journal resolves to, so hiding them would leave a reviewer's name pointing
         *     at nothing.
         */
        get: operations["listAccounts"];
        put?: never;
        /**
         * Make an account for a person
         * @description There is no open sign-up: an account exists because an administrator made it
         *     (`product.md` §8.2). No password is stored — the address is how they sign
         *     in, so there is nothing to forget and nothing to reset
         *     ([ADR 0019](https://github.com/haribo/ozalid/blob/develop/docs/adr/0019-two-kinds-of-account-one-set-of-rights.md)).
         *
         *     The new account reaches nothing until somebody grants it a membership.
         */
        post: operations["createAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accounts/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop an account from signing in
         * @description Deactivated, never deleted. Every fact it recorded keeps naming it, and the
         *     journal holds no foreign key to the account table precisely so evidence
         *     outlives the person ([ADR 0018](https://github.com/haribo/ozalid/blob/develop/docs/adr/0018-an-actor-is-never-invented.md)).
         *
         *     Idempotent: deactivating an account that is already deactivated changes
         *     nothing and answers the same.
         */
        delete: operations["deactivateAccount"];
        options?: never;
        head?: never;
        /**
         * Promote or demote an account
         * @description An ordinary administrative act, and the reason a role set wrongly when the
         *     account was made is not permanent.
         *
         *     **The last administrator cannot be demoted.** An instance with nobody
         *     administering it can no longer make an account, grant a membership or mint a
         *     token, and nothing short of a database console repairs that.
         */
        patch: operations["setAccountRole"];
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The projects this caller may see
         * @description The ones they belong to — and every one on the instance when they administer
         *     it. An administrator names a project to manage its membership, and a power
         *     that cannot be exercised is not a power (`product.md` §8.2). What stays
         *     withheld is everything inside: the cases, the captures, the remarks.
         *
         *     A service account belongs to one project and sees that one
         *     ([ADR 0018](https://github.com/haribo/ozalid/blob/develop/docs/adr/0018-an-actor-is-never-invented.md)).
         */
        get: operations["listProjects"];
        put?: never;
        /** Open a book */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Read a project */
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/axes": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Read the project's rendering axes, in their declared order */
        get: operations["listAxes"];
        /**
         * Declare the order the axes read in
         * @description Only the order. Axes themselves are created by first use at intake —
         *     ozalid ships no list of them and never invents one.
         *
         *     The order is what a variant's label reads from: placing `viewport` before
         *     `theme` turns `dark·desktop` into `desktop·dark`. Existing variants are
         *     relabelled, since a label is a rendering of the values and never an
         *     identity.
         *
         *     An axis the project omits keeps its place after those it named.
         */
        put: operations["orderAxes"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/cases": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /**
         * List the catalogue
         * @description Filters on the stored state, without scanning — which is why the state is
         *     stored at all. Archived cases are never listed.
         */
        get: operations["listCases"];
        put?: never;
        /**
         * Open a case and receive its id
         * @description The id comes back generated; the client stores it and sends it on every
         *     subsequent edition. It never invents one.
         */
        post: operations["createCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/editions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a run's evidence into the book
         * @description Push the complete manifest. Ask `HEAD /blobs/{hash}` first and upload what
         *     the store does not hold — a manifest referencing absent content is refused
         *     with the list of addresses to send.
         *
         *     The edition is written in one transaction: it exists whole, or not at all.
         *     There is no pending edition.
         */
        post: operations["createEdition"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/service-accounts": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Make a program an account on this project
         * @description A service account belongs to exactly one project, and that is enforced by a
         *     partial unique index rather than trusted
         *     ([ADR 0018](https://github.com/haribo/ozalid/blob/develop/docs/adr/0018-an-actor-is-never-invented.md)).
         *     It is created here, with the project, and never moves.
         *
         *     **Administration, not membership.** Creating one is granting a membership,
         *     and an administrator grants memberships (`product.md` §8.2). A member of the
         *     project could otherwise mint a credential that keeps working after their own
         *     membership is revoked — a program nobody remembers, holding rights nobody
         *     reviews.
         *
         *     The token comes back in the response and nowhere else.
         */
        post: operations["createServiceAccount"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/service-accounts/{serviceAccountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retire a program
         * @description Deactivated, never deleted: the journal names it, and evidence has to
         *     survive the account that produced it
         *     ([ADR 0018](https://github.com/haribo/ozalid/blob/develop/docs/adr/0018-an-actor-is-never-invented.md)).
         *     Its tokens stop opening anything at once.
         *
         *     Idempotent: retiring one already retired changes nothing.
         */
        delete: operations["deactivateServiceAccount"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/service-accounts/{serviceAccountId}/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
            };
            cookie?: never;
        };
        /**
         * What tokens this program holds
         * @description Their labels and when they were last presented, never the tokens: only a
         *     hash was ever stored, so there is nothing here to give back.
         *
         *     `lastUsedAt` is what makes a rotation finishable — it tells an operator
         *     which of the old tokens nothing uses any more.
         */
        get: operations["listServiceTokens"];
        put?: never;
        /**
         * Mint another token for this program
         * @description Adds one; it does not retire the others. That is what makes a rotation
         *     survivable: deploy the new token, watch `lastUsedAt` on the old one stop
         *     moving, then delete it. Retiring on mint would take the pipeline down at the
         *     moment somebody was trying to make it safer.
         */
        post: operations["mintServiceToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/service-accounts/{serviceAccountId}/tokens/{tokenId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
                tokenId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Stop one token working
         * @description The account keeps its other tokens. This is the second half of a rotation,
         *     and the half that is easy to forget — a token nobody retires is a
         *     credential nobody is watching.
         *
         *     Idempotent: retiring one that is already gone changes nothing.
         */
        delete: operations["retireServiceToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /**
         * Who reaches this project
         * @description People and programs in one list. A service account holds a membership like
         *     anyone else ([ADR 0019](https://github.com/haribo/ozalid/blob/develop/docs/adr/0019-two-kinds-of-account-one-set-of-rights.md)),
         *     and hiding either kind would make the list a lie about who can see the book.
         *
         *     Reaching this needs `reader`, not administration: seeing who is on a project
         *     is seeing, and a reader sees everything (`product.md` §8.1).
         */
        get: operations["listMembers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/members/{accountId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                accountId: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Put a person on a project, or change what they may do
         * @description An administrator grants memberships — all of them, not only the first
         *     (`product.md` §8.2). Granting to somebody who is already a member changes
         *     their rights rather than failing: an administrator who meant to demote
         *     somebody said so, and refusing would make them revoke first and risk
         *     forgetting the second half.
         *
         *     Names a **person**. A service account's membership is written when it is
         *     created and never moved: it belongs to one project, and that is enforced
         *     rather than trusted ([ADR 0018](https://github.com/haribo/ozalid/blob/develop/docs/adr/0018-an-actor-is-never-invented.md)).
         */
        put: operations["grantMembership"];
        post?: never;
        /**
         * Take a person off a project
         * @description They stop reaching it. Everything they recorded stays, and keeps naming
         *     them: the journal holds no foreign key to any account table precisely so
         *     evidence outlives a membership (`product.md` §8).
         *
         *     Idempotent: revoking a membership nobody holds changes nothing and answers
         *     the same.
         */
        delete: operations["revokeMembership"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/categories": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        /** Read the catalogue tree */
        get: operations["listCategories"];
        put?: never;
        /** Add a node to the tree */
        post: operations["createCategory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/captures/{captureId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                captureId: string;
            };
            cookie?: never;
        };
        /**
         * The image a capture holds
         * @description Read through the capture, never through the content address. A hash names
         *     no project — identical bytes are stored once for every project that
         *     references them
         *     ([ADR 0004](https://github.com/haribo/ozalid/blob/develop/docs/adr/0004-content-addressed-capture-storage.md)) —
         *     so there is nothing there to check a membership against. A capture has a
         *     row, a case and therefore one project (`product.md` §8.1).
         *
         *     The response is immutable: a capture's bytes never change, because a new
         *     run produces a new capture rather than overwriting one.
         */
        get: operations["getCaptureImage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/recordings/{recordingId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                recordingId: string;
            };
            cookie?: never;
        };
        /**
         * The video a recording holds
         * @description Read through the recording, for the same reason a capture's image is
         *     (`product.md` §8.1). A recording is a supporting exhibit: never
         *     byte-compared, never a source of state (ADR 0013).
         */
        get: operations["getRecordingVideo"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/cases/{caseId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        /** Read a case, archived or not */
        get: operations["getCase"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Change what is mutable about a case
         * @description Its id and its state are not part of that.
         */
        patch: operations["updateCase"];
        trace?: never;
    };
    "/projects/{slug}/cases/{caseId}/captures": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        /**
         * Read the evidence a case is judged from
         * @description The grid: steps in order, the variants that exist, and the capture sitting
         *     at each cell. A cell with no capture is simply absent — not every variant
         *     exists at every step.
         *
         *     Defaults to the project's most recent edition. A specific one can be asked
         *     for, since a case may sit on an older edition while it is being reviewed.
         *
         *     A case that has never been captured answers with an empty grid, not an
         *     error: not being instrumented is a legitimate state.
         */
        get: operations["getCaseCaptures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/cases/{caseId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        /**
         * Read what has been said about a case
         * @description Settled comments included. Nothing is deleted, and a discarded one stays
         *     visible with its reason and its author — "I reported this three months ago,
         *     who removed it?" must always have an answer (ADR 0006).
         */
        get: operations["listComments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/comments/{commentId}/reference": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Attach an external issue to a comment
         * @description The identifier, the URL and the title are **supplied by the client**.
         *     ozalid never fetches them, never refreshes them, and will never know the
         *     issue was closed — it holds no tracker credential and wants none
         *     (ADR 0003).
         */
        post: operations["trackComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/comments/{commentId}/discard": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set a comment aside
         * @description The reason is mandatory, and kept forever with its author. The friction is
         *     intended: a defect dismissed without a reason is exactly what comes back
         *     in six months. Nothing is deleted — a discarded comment stays visible on
         *     its case (ADR 0006).
         */
        post: operations["discardComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/comments/{commentId}/delivery": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask for a judgment on a delivered fix
         * @description The dev saying "I finished this, look". Only they know it — captures also
         *     move for a refactor or a dependency bump, and summoning the reviewer for
         *     that is noise.
         *
         *     They may ask without having implemented everything else on the case: one
         *     issue can depend on the verdict given on another.
         */
        post: operations["deliverComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/comments/{commentId}/judgment": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept a delivery, or refuse it
         * @description A refusal carries a mandatory remark and is **not** a way to die: the dev
         *     reworks and delivers again, as many rounds as it takes. Every judgment is
         *     kept, so three round trips on one comment stay visible.
         */
        post: operations["judgeComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/cases/{caseId}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save what one review session decided
         * @description One save carries everything the sitting produced: the squares looked at with
         *     nothing to say, and the comments written on the rest. Splitting it would
         *     leave a case half-judged between two calls.
         *
         *     The server works out what it means. **No endpoint accepts a case state** —
         *     it is computed from the comments and the verdicts, never received
         *     (ADR 0002, ADR 0012).
         */
        post: operations["saveReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/cases/{caseId}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Take a case out of the catalogue
         * @description It stops being listed and stops blocking intake, and stays readable with its
         *     captures, comments and journal. There is no deletion.
         */
        post: operations["archiveCase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{slug}/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                categoryId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an empty node
         * @description Only an empty one. Deleting a filing drawer must not silently move what was
         *     inside it, so a category holding a sub-category or a case is refused.
         *
         *     An **archived** case counts as content: it still records where it was filed,
         *     and an archived case is meant to stay whole. Move it first if the category
         *     has to go.
         */
        delete: operations["deleteCategory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: components["schemas"]["problem"];
        problem: {
            /**
             * Format: uri
             * @description A URI identifying the problem type.
             * @example https://ozalid.dev/problems/case-not-found
             */
            type: string;
            /** @description A short, human-readable summary, stable for a given type. */
            title: string;
            /** @description The HTTP status code. */
            status: number;
            /** @description An explanation specific to this occurrence. */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
        Account: {
            id: string;
            name: string;
            /** Format: email */
            email: string;
            /** @description Manages accounts and creates projects; reaches no content. */
            isAdmin: boolean;
            /**
             * Format: date-time
             * @description Absent while the account works. An account is deactivated, never
             *     deleted: what it reviewed stays readable and the journal keeps naming
             *     it (ADR 0018).
             */
            deactivatedAt?: string;
            /** Format: date-time */
            createdAt: string;
        };
        NewAccount: {
            name: string;
            /**
             * Format: email
             * @description Unique, and where the sign-in link is sent. There is no password.
             */
            email: string;
            /** @default false */
            isAdmin: boolean;
        };
        Project: {
            id: string;
            slug: string;
            name: string;
            /**
             * @description `strict` refuses intake while any case is to-review; `per-case` never
             *     refuses.
             * @enum {string}
             */
            intakePolicy: "strict" | "per-case";
            /** Format: date-time */
            createdAt: string;
            /**
             * @description How many people reach this project. Deactivated accounts are not
             *     counted: they reach nothing (`product.md` §8.2).
             */
            people: number;
            /** @description How many programs reach it. */
            programs: number;
        };
        NewProject: {
            slug: string;
            name: string;
            /**
             * @default per-case
             * @enum {string}
             */
            intakePolicy: "strict" | "per-case";
        };
        /**
         * @description A rendering dimension the project declares. ozalid ships no built-in list:
         *     an axis exists because a capture mentioned it.
         */
        Axis: {
            name: string;
            /** @description Where it reads in a variant's label. Lower comes first. */
            position: number;
        };
        /**
         * @description Who holds the ball. Computed by the server from the case's comments; no
         *     endpoint accepts it as an argument.
         * @enum {string}
         */
        CaseState: "not-instrumented" | "to-review" | "to-fix" | "reviewed";
        /**
         * @description How this case's captures stand at the edition it points at. A capture with
         *     no verdict yet counts as still to judge.
         */
        CaptureCounts: {
            total: number;
            validated: number;
            commented: number;
            toJudge: number;
        };
        Case: {
            /** @description Generated by the server when the case was created. Stable forever. */
            id: string;
            projectId: string;
            categoryId?: string | null;
            title: string;
            description?: string | null;
            state: components["schemas"]["CaseState"];
            /** @description An archived case leaves the catalogue but stays readable. */
            archived: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            captures?: components["schemas"]["CaptureCounts"];
            /** Format: date-time */
            lastEdition?: string | null;
        };
        NewCase: {
            title: string;
            description?: string;
            categoryId?: string;
        };
        /**
         * @description A combination of axis values, such as `{"theme":"dark","viewport":"mobile"}`.
         *     The project declares its own axes — ozalid ships no list. An axis the client
         *     does not supply is simply absent: a site with no theme has no theme.
         * @example {
         *       "theme": "dark",
         *       "viewport": "mobile",
         *       "locale": "fr"
         *     }
         * @example {
         *       "locale": "en"
         *     }
         */
        Variant: {
            [key: string]: string;
        };
        /**
         * @description Where the capture was produced. Byte comparison only means something within
         *     one environment, so this is recorded and never guessed.
         */
        Provenance: {
            os?: string;
            browser?: string;
            browserVersion?: string;
            /** @description The effective resolution, recorded as provenance and never as identity. */
            resolution?: string;
            environmentId?: string;
        };
        ManifestCapture: {
            variant: components["schemas"]["Variant"];
            hash: string;
            provenance?: components["schemas"]["Provenance"];
        };
        ManifestStep: {
            name: string;
            captures: components["schemas"]["ManifestCapture"][];
        };
        ManifestRecording: {
            variant: components["schemas"]["Variant"];
            hash: string;
        };
        ManifestCase: {
            /** @description The id ozalid generated when the case was created. */
            id: string;
            steps: components["schemas"]["ManifestStep"][];
            /** @description The flow video per variant. Optional, and never compared byte-wise. */
            recordings?: components["schemas"]["ManifestRecording"][];
        };
        Manifest: {
            /**
             * @description Opaque to ozalid: displayed, never computed on. A commit hash, a build
             *     number — whatever the client means by "which version produced this".
             */
            revision?: string;
            cases: components["schemas"]["ManifestCase"][];
        };
        EditionAccepted: {
            editionId: string;
            cases: number;
            captures: number;
            recordings: number;
        };
        IntakeRefused: components["schemas"]["problem"] & {
            /** @description The addresses to upload before pushing again. */
            missingContent?: string[];
            /**
             * @description The addresses of captures that are not PNG. A separate field from
             *     `missingContent` on purpose: the store holds these bytes, so
             *     uploading them again would fix nothing. They have to be re-captured.
             */
            notAPng?: string[];
        };
        /**
         * @description `reader` sees everything and changes nothing; `member` does everything, on
         *     the projects they belong to. Two, and no more (`product.md` §8.1).
         * @enum {string}
         */
        Rights: "reader" | "member";
        NewServiceAccount: {
            name: string;
            rights?: components["schemas"]["Rights"];
            /** @description What the first token is for, in a human's words. */
            tokenLabel: string;
        };
        ServiceAccount: {
            id: string;
            name: string;
            /** Format: date-time */
            createdAt: string;
        };
        MintedToken: {
            id: string;
            label: string;
            /**
             * @description **Shown once and never again.** Only its hash is stored, so nothing here
             *     can give it back — a lost token is replaced, not recovered.
             */
            token: string;
            /** Format: date-time */
            createdAt: string;
        };
        ServiceToken: {
            id: string;
            /** @description A token nobody can name is a token nobody dares retire. */
            label: string;
            /** Format: date-time */
            createdAt: string;
            /**
             * Format: date-time
             * @description Absent while nothing has ever presented it. It is what tells an operator
             *     which tokens are still in use and which can go.
             */
            lastUsedAt?: string;
        };
        NewToken: {
            label: string;
        };
        Membership: {
            accountId: string;
            name: string;
            /**
             * Format: email
             * @description Absent for a service account, which has no address to reach.
             */
            email?: string;
            /**
             * @description Whether this member is a person or a program. Derived from which kind of
             *     account holds the membership, never declared
             *     (`product.md` §8).
             */
            isPerson: boolean;
            rights: components["schemas"]["Rights"];
            /**
             * @description How many credentials this program holds. Absent for a person, who
             *     presents no token. **Zero is the value worth seeing**: a member that
             *     cannot authenticate, which is a missing key rather than a retired
             *     account — a retired account is not listed here at all (`product.md`
             *     §8.2).
             */
            tokens?: number;
            /** Format: date-time */
            addedAt: string;
        };
        NewMembership: {
            rights: components["schemas"]["Rights"];
        };
        /**
         * @description How many cases sit in each state under this node, across its **whole
         *     descendance** — not just its direct children. A branch in trouble has to be
         *     visible from the root.
         */
        StateCounts: {
            notInstrumented: number;
            toReview: number;
            toFix: number;
            reviewed: number;
        };
        Category: {
            id: string;
            parentId?: string | null;
            name: string;
            position: number;
            cases: components["schemas"]["StateCounts"];
            /** Format: date-time */
            lastActivity?: string | null;
        };
        NewCategory: {
            name: string;
            parentId?: string;
            /** @default 0 */
            position: number;
        };
        CaseUpdate: {
            title: string;
            description?: string | null;
            categoryId?: string | null;
        };
        GridVariant: {
            id: string;
            /** @description A readable rendering of the combination, such as `dark·mobile`. */
            label: string;
            values: {
                [key: string]: string;
            };
        };
        GridCell: {
            /**
             * @description The capture. Fetch its image at
             *     `/projects/{slug}/captures/{captureId}` — the hash names no project and
             *     cannot be authorised (`product.md` §8.1).
             */
            id: string;
            variantId: string;
            /**
             * @description The content address these bytes are stored under. What a client
             *     computes before uploading, not what a reader fetches with.
             */
            hash: string;
            /**
             * @description Where this square stands. Computed by the server from the comments
             *     covering it — never set by a caller (ADR 0012).
             * @enum {string}
             */
            status: "to-review" | "to-fix" | "validated";
            /**
             * @description Whether this capture still shows what a reviewer approved, computed once
             *     when it arrived. **Absent means nothing to compare against** — nobody has
             *     approved this square in this capture's environment — which is not the
             *     same as unchanged (ADR 0017).
             *
             *     Freshness is an overlay, never a state: a `reviewed` case whose captures
             *     move stays `reviewed` until its reviewer says otherwise.
             * @enum {string}
             */
            freshness?: "current" | "to-re-review";
            /**
             * @description How many pixels differed by more than the fixed per-channel tolerance.
             *     Recorded so a project can judge its threshold rather than guess it.
             *
             *     Absent when no pixel reading happened: identical addresses need none, and
             *     images of different dimensions admit none.
             */
            movedPixels?: number;
            provenance?: components["schemas"]["Provenance"];
        };
        GridStep: {
            id: string;
            name: string;
            position: number;
            /** @description One entry per variant that has a capture at this step. */
            cells: components["schemas"]["GridCell"][];
        };
        GridRecording: {
            /** @description Fetch the video at `/projects/{slug}/recordings/{recordingId}`. */
            id: string;
            variantId: string;
            hash: string;
        };
        Grid: {
            caseId: string;
            /** @description Absent when the project has taken nothing in yet. */
            editionId?: string;
            /**
             * @description What the client declared this edition was built from. Displayed, never
             *     computed on.
             */
            revision?: string;
            /** Format: date-time */
            takenAt?: string;
            /** @description The variants present in this edition, in label order. */
            variants: components["schemas"]["GridVariant"][];
            steps: components["schemas"]["GridStep"][];
            recordings: components["schemas"]["GridRecording"][];
        };
        /**
         * @description Where the comment stands. `validated` and `discarded` are the only terminal
         *     states; a refusal returns to `to-review` on the next delivery.
         * @enum {string}
         */
        CommentState: "to-track" | "tracked" | "to-review" | "refused" | "validated" | "discarded";
        /**
         * @description An opaque reference to an issue somewhere else. Supplied by the client and
         *     never read back: ozalid holds no tracker credential (ADR 0003).
         */
        IssueRef: {
            id: string;
            /** Format: uri */
            url?: string;
            /**
             * @description Shown next to the comment. ozalid never refreshes it, so it is whatever
             *     the client said at the time.
             */
            title?: string;
        };
        Judgment: {
            /** @enum {string} */
            verdict: "accepted" | "refused";
            /** @description Mandatory on a refusal. It is what the dev has to read. */
            remark?: string;
            actorId: string;
            /** Format: date-time */
            at: string;
        };
        Comment: {
            id: string;
            stepId: string;
            /** @enum {string} */
            kind: "defect" | "improvement";
            /** @description What the reviewer wrote, in their words. It survives the issue title. */
            body: string;
            state: components["schemas"]["CommentState"];
            variantIds: string[];
            issue?: components["schemas"]["IssueRef"];
            /** @description Mandatory when discarded, and kept forever with its author. */
            discardReason?: string;
            authorId: string;
            /** Format: date-time */
            createdAt: string;
            /** @description Every judgment, not just the last — three round trips is information. */
            judgments: components["schemas"]["Judgment"][];
        };
        MoveOutcome: {
            commentState: components["schemas"]["CommentState"];
            caseState: components["schemas"]["CaseState"];
        };
        CellRef: {
            stepId: string;
            variantId: string;
        };
        NewComment: {
            stepId: string;
            /**
             * @description What it is. The kind is written on the comment, where it is exact and
             *     where the issue is written from — it never colours the case's state.
             * @enum {string}
             */
            kind: "defect" | "improvement";
            body: string;
            /**
             * @description The variants it applies to. One defect spanning four variants is **one**
             *     comment with four variants checked, never four comments.
             */
            variantIds: string[];
        };
        ReviewSave: {
            /** @description The squares the reviewer looked at with nothing to say. */
            validated?: components["schemas"]["CellRef"][];
            /** @description What the reviewer wrote during the sitting. */
            comments?: components["schemas"]["NewComment"][];
        };
        CellVerdict: components["schemas"]["CellRef"] & {
            /** @enum {string} */
            status: "to-review" | "to-fix" | "validated";
        };
        ReviewOutcome: {
            state: components["schemas"]["CaseState"];
            /** @description How many comments the session added. */
            comments: number;
            /** @description The status of every capture the case has, after the save. */
            verdicts: components["schemas"]["CellVerdict"][];
        };
    };
    responses: {
        /** @description The request is malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
        /** @description The caller presented no usable credential. */
        Unauthenticated: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
        /** @description The caller is known and not allowed to do this. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
        /** @description Where the comment and its case now stand. */
        MoveApplied: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["MoveOutcome"];
            };
        };
        /**
         * @description The move does not exist from where the comment stands, or it is already
         *     settled.
         */
        MoveRefused: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
    };
    parameters: {
        Slug: string;
        CommentId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /**
                         * @description The build this instance runs.
                         * @example 0.1.0
                         */
                        version: string;
                    };
                };
            };
        };
    };
    requestSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                };
            };
        };
        responses: {
            /** @description If that address has an account, a link is on its way. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /**
             * @description Too many links asked for. The ones already sent still work — a link
             *     stays good for fifteen minutes.
             */
            429: {
                headers: {
                    /** @description Seconds until the window turns over. */
                    "Retry-After"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    claimSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    link: string;
                };
            };
        };
        responses: {
            /** @description Signed in. The session is in the response's cookie. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    signOut: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Signed out, or was not signed in — the same answer. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    whoAmI: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in person. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        id: string;
                        name: string;
                        email: string;
                        /** @description Manages accounts and creates projects; reaches no content. */
                        isAdmin: boolean;
                    };
                };
            };
            401: components["responses"]["Unauthenticated"];
        };
    };
    putBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description The content is stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The store already held this content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description The bytes do not produce the announced address. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    headBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The store holds this content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description The store does not hold this content. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAccounts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The accounts, by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewAccount"];
            };
        };
        responses: {
            /** @description The account. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Account"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description That address already has an account. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    deactivateAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account can no longer sign in. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description It would leave the instance with no administrator. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    setAccountRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    isAdmin: boolean;
                };
            };
        };
        responses: {
            /** @description The role is what was asked for. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description It would leave the instance with no administrator. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The projects, by name. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewProject"];
            };
        };
        responses: {
            /** @description The project is open. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            /** @description That slug is taken. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The project. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listAxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The axes. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Axis"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    orderAxes: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * @description Axis names, most significant first.
                     * @example [
                     *       "viewport",
                     *       "theme",
                     *       "locale"
                     *     ]
                     */
                    order: string[];
                };
            };
        };
        responses: {
            /** @description The axes in their new order. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Axis"][];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listCases: {
        parameters: {
            query?: {
                state?: components["schemas"]["CaseState"];
                categoryId?: string;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The cases. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCase"];
            };
        };
        responses: {
            /** @description The case is open, outside the funnel until it has captures. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createEdition: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Manifest"];
            };
        };
        responses: {
            /** @description The edition is in the book. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EditionAccepted"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /**
             * @description The manifest cannot be taken in: content is missing, a case is unknown
             *     or named twice, or the project runs `strict` and a review is open.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["IntakeRefused"];
                };
            };
        };
    };
    createServiceAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewServiceAccount"];
            };
        };
        responses: {
            /** @description The account, and its first token — once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        account: components["schemas"]["ServiceAccount"];
                        token: components["schemas"]["MintedToken"];
                    };
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    deactivateServiceAccount: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description It reaches nothing any more. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listServiceTokens: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tokens, newest first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceToken"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    mintServiceToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewToken"];
            };
        };
        responses: {
            /** @description The token — once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MintedToken"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    retireServiceToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                serviceAccountId: string;
                tokenId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description That token opens nothing. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listMembers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The members, people first. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    grantMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewMembership"];
            };
        };
        responses: {
            /** @description They are a member with those rights. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    revokeMembership: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                accountId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description They no longer reach this project. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The tree, parents before children. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    createCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCategory"];
            };
        };
        responses: {
            /** @description The category. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description A sibling already carries that name. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    getCaptureImage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                captureId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The image. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/png": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getRecordingVideo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                recordingId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The video. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseUpdate"];
            };
        };
        responses: {
            /** @description The updated case. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Case"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    getCaseCaptures: {
        parameters: {
            query?: {
                editionId?: string;
            };
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The evidence. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Grid"];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    listComments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The comments. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"][];
                };
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    trackComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IssueRef"];
            };
        };
        responses: {
            200: components["responses"]["MoveApplied"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MoveRefused"];
        };
    };
    discardComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    reason: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MoveApplied"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MoveRefused"];
        };
    };
    deliverComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MoveApplied"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MoveRefused"];
        };
    };
    judgeComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: components["parameters"]["Slug"];
                commentId: components["parameters"]["CommentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    accept: boolean;
                    /** @description Mandatory when refusing. It is what the dev has to read. */
                    remark?: string;
                };
            };
        };
        responses: {
            200: components["responses"]["MoveApplied"];
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["MoveRefused"];
        };
    };
    saveReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewSave"];
            };
        };
        responses: {
            /** @description What the session amounted to. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewOutcome"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    archiveCase: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                caseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The case is archived. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The case was already archived. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    deleteCategory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                categoryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The category is gone. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthenticated"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description The category is not empty. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
}
