/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the service is able to serve */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/blobs/{hash}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        /** Download the content at this address */
        get: operations["getBlob"];
        /**
         * Store content under its address
         * @description Idempotent: storing content that is already held changes nothing. The bytes
         *     are refused if they do not produce the announced address — content sitting
         *     at an address that does not describe it would hand every future reader the
         *     wrong evidence with no way to notice.
         *
         *     When the address is already held the upload is answered `204` without the
         *     body being read at all, so a client sending the wrong bytes under a known
         *     address is not told. The stored content is still correct; verifying would
         *     mean reading every upload in full, which is the cost this avoids. Call
         *     `HEAD` first and skip what is already held.
         */
        put: operations["putBlob"];
        post?: never;
        delete?: never;
        options?: never;
        /**
         * Report whether the store already holds this content
         * @description Intake calls this before sending bytes: content already held is never
         *     uploaded again, which is what makes a full visual history affordable.
         */
        head: operations["headBlob"];
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: components["schemas"]["problem"];
        problem: {
            /**
             * Format: uri
             * @description A URI identifying the problem type.
             * @example https://ozalid.dev/problems/case-not-found
             */
            type: string;
            /** @description A short, human-readable summary, stable for a given type. */
            title: string;
            /** @description The HTTP status code. */
            status: number;
            /** @description An explanation specific to this occurrence. */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
    };
    responses: {
        /** @description The request is malformed. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
        /** @description No such resource. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /**
                         * @description The build this instance runs.
                         * @example 0.1.0
                         */
                        version: string;
                    };
                };
            };
        };
    };
    getBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/octet-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
        };
    };
    putBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/octet-stream": string;
            };
        };
        responses: {
            /** @description The content is stored. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description The store already held this content. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description The bytes do not produce the announced address. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["problem"];
                };
            };
        };
    };
    headBlob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The content address, as `sha256:` followed by 64 lowercase hex characters. */
                hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The store holds this content. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description The store does not hold this content. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
