/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Report whether the service is able to serve */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: components["schemas"]["problem"];
        problem: {
            /**
             * Format: uri
             * @description A URI identifying the problem type.
             * @example https://ozalid.dev/problems/case-not-found
             */
            type: string;
            /** @description A short, human-readable summary, stable for a given type. */
            title: string;
            /** @description The HTTP status code. */
            status: number;
            /** @description An explanation specific to this occurrence. */
            detail?: string;
            /** Format: uri-reference */
            instance?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is serving. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /**
                         * @description The build this instance runs.
                         * @example 0.1.0
                         */
                        version: string;
                    };
                };
            };
        };
    };
}
