//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Problem defines model for problem.
type Problem struct {
	// Detail An explanation specific to this occurrence.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title A short, human-readable summary, stable for a given type.
	Title string `json:"title"`

	// Type A URI identifying the problem type.
	//
	// Examples: https://ozalid.dev/problems/case-not-found
	Type string `json:"type"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetBlob Download the content at this address
	// (GET /blobs/{hash})
	GetBlob(w http.ResponseWriter, r *http.Request, hash string)
	// HeadBlob Report whether the store already holds this content
	// (HEAD /blobs/{hash})
	HeadBlob(w http.ResponseWriter, r *http.Request, hash string)
	// PutBlob Store content under its address
	// (PUT /blobs/{hash})
	PutBlob(w http.ResponseWriter, r *http.Request, hash string)
	// GetHealth Report whether the service is able to serve
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBlob operation middleware
func (siw *ServerInterfaceWrapper) GetBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadBlob operation middleware
func (siw *ServerInterfaceWrapper) HeadBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutBlob operation middleware
func (siw *ServerInterfaceWrapper) PutBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/blobs/{hash}", wrapper.GetBlob)
	m.HandleFunc(http.MethodHead+" "+options.BaseURL+"/blobs/{hash}", wrapper.HeadBlob)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/blobs/{hash}", wrapper.PutBlob)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type GetBlobRequestObject struct {
	Hash string `json:"hash"`
}

type GetBlobResponseObject interface {
	VisitGetBlobResponse(w http.ResponseWriter) error
}

type GetBlob200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetBlob200ApplicationoctetStreamResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetBlob400ApplicationProblemPlusJSONResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBlob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetBlob404ApplicationProblemPlusJSONResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type HeadBlobRequestObject struct {
	Hash string `json:"hash"`
}

type HeadBlobResponseObject interface {
	VisitHeadBlobResponse(w http.ResponseWriter) error
}

type HeadBlob200Response struct {
}

func (response HeadBlob200Response) VisitHeadBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HeadBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response HeadBlob400ApplicationProblemPlusJSONResponse) VisitHeadBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type HeadBlob404Response struct {
}

func (response HeadBlob404Response) VisitHeadBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutBlobRequestObject struct {
	Hash string `json:"hash"`
	Body io.Reader
}

type PutBlobResponseObject interface {
	VisitPutBlobResponse(w http.ResponseWriter) error
}

type PutBlob201Response struct {
}

func (response PutBlob201Response) VisitPutBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutBlob204Response struct {
}

func (response PutBlob204Response) VisitPutBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutBlob400ApplicationProblemPlusJSONResponse) VisitPutBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutBlob422ApplicationProblemPlusJSONResponse Problem

func (response PutBlob422ApplicationProblemPlusJSONResponse) VisitPutBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status GetHealth200JSONResponseBodyStatus `json:"status"`

	// Version The build this instance runs.
	//
	// Examples: 0.1.0
	Version string `json:"version"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetBlob Download the content at this address
	// (GET /blobs/{hash})
	GetBlob(ctx context.Context, request GetBlobRequestObject) (GetBlobResponseObject, error)
	// HeadBlob Report whether the store already holds this content
	// (HEAD /blobs/{hash})
	HeadBlob(ctx context.Context, request HeadBlobRequestObject) (HeadBlobResponseObject, error)
	// PutBlob Store content under its address
	// (PUT /blobs/{hash})
	PutBlob(ctx context.Context, request PutBlobRequestObject) (PutBlobResponseObject, error)
	// GetHealth Report whether the service is able to serve
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBlob operation middleware
func (sh *strictHandler) GetBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request GetBlobRequestObject

	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBlob(ctx, request.(GetBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBlobResponseObject); ok {
		if err := validResponse.VisitGetBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadBlob operation middleware
func (sh *strictHandler) HeadBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request HeadBlobRequestObject

	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeadBlob(ctx, request.(HeadBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeadBlobResponseObject); ok {
		if err := validResponse.VisitHeadBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutBlob operation middleware
func (sh *strictHandler) PutBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request PutBlobRequestObject

	request.Hash = hash

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutBlob(ctx, request.(PutBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutBlobResponseObject); ok {
		if err := validResponse.VisitPutBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"vFfNchu5EX6VLsS3DH9ES4rMnOw4iXxxuRyncjCVUg/QQ8DCALMAhjRXxap9iH3CfZKtBkiKFGnZW+X1",
	"bTgYdDe+/r4PzXshfdt5Ry5FMb0XgWLnXaT84xWq9/RTTzHxL+ldIpcfseuskZiMd6Mu+NpS+9dP0Tte",
	"i1JTi/z0LFAjpuIvo4cUo7Iat7vEer2uhKIog+k4nJiKD5oglLRgIrRoGx9aUkOxrsRbn/7le6d+ZEFv",
	"PcReaggUfR8kDQV/s9nIcbd7y2NHIZkCoKKExpan/YgvHdDnzqLLFUPsSJrGSEgekjYRvJR9COQ4VyXS",
	"qiMxFTEF4+YMgnExoZPEgRkbTGIq+mAGgRrK207tiglTH4+LYbyvP3x4B+UDkF7tpzUu0ZwCR0gmWTpx",
	"Gojah1SB7lt0g0CosLYEsW9bDKuKA/PvxgdAmJsFOeDgJ89WXhyn+O/7N2AUuWSalXFzSJpgg/suGH3G",
	"trMM/UehU+ridDTyP6M1aqhosW1xHEmMNHA+DZpMpZvqAMXjqtaVYEKaQIpD59UtGjtcb3bbfP2JZCpM",
	"Mq7xp46jfUykINDC0BJq7+8yPOTUIPkBOQWJ+U8LPvOGBgV9UU4kKrGgEEu88fBsOGb0fEcOOyOm4nl+",
	"VYkOk85NH9XW13F0rzHqNb+YU5YO8zXT8I0SU/FvSq+sr0V16AST8fgJxXmZKA1iCoTtoeJ2uNbGYVid",
	"gPak/Dd5suLPS+pT2t2VONpzqrzl/Otbdk6SxVyoKqbitV8661Flgm3qAExFl6hUoBj5GDjPNMugipt1",
	"JTShOu70G5fwjkCitbHEqKnxgSCSU8zjepUoTh8yWZbPCjRZxe7naEFh5vqOayIFOEfjKlhqIzWvLzUm",
	"aPGOIiA0vbWwMLFHC9rE5MMKsGl8yHoczpyoHrX7mlA90e/jznBQAu2t2hzn+7TqS4mUpwjOp5zxccKD",
	"vr2nzocES01JU8jdKyF2iB7VfLKNHQZsKVHg9/df5uaWCxVghNuocXJxOb2Fxlvrl6SgXsHlOfBzYLsB",
	"TZ9BagwoOfahW90LiV3qQza+Bdo+K6SEfNFcXarx1dnV1bn8m7q8eIGThhDH8uIC1fjsAp/XzXlzVk/q",
	"cX01mUh1dqEu5dlFPW7GYxxfieJCYpqdQFTCYcvh2QbEvq+l0FO1J90OU6LAG/+/KeXjePACB83N/eX5",
	"+tkJKd9UouvTCQ0oajvPoE1zT5j2WxQT85eVtc97qdHNS+O1cfMhMO5ZKDOHgaeDpo+kwDTc5xUonznS",
	"Ba96Sbn36JzvnWTFlD7Bb7/8ussaTUrGzWcOE6DbfZKL2VGuHKImMAmWvrcKNDoFLMgVND33C7jowraZ",
	"Wwbv5jvHhqVJGpyHJa74Xnc+GckanLn/ab4AuchN3sfn57Wi+Lzk4pICKbidjM9vc1zfp5Kz9moFNTGi",
	"vJ+NCq2tIHpAkNbkw26chqOWGjOU0DsuHeHO+aWbub1i+PTJW1WAzzJSO+xMhJiMtSB9CCTT32FBYXMp",
	"Z5hmriV0uR6TAWG8tsdx2aT2DKzYbNwa7MIbFYfwD7R25m6v//ny9S00JkTuk4J4Z7pieY8gO+Vt7/qH",
	"qyz7zSuvVn/eLXaopPWRoZ6d9rkDWBno7KSTp23xEVu+gw1PJj96xC8k/BbpPrb6/2QMtsAVGpv01O28",
	"rsRIE9qknxp8rssXf2j0OYbk8B/Aw9BNrm+5Jn+3Nyo+zL27Ye5U1+vebBu9nf0h9C4+HnrLHHjztQF2",
	"U9RD0tOz6wn2UVgYSZms/Ojm33INP2zKfwOSz69or0+bT7hTHI1XN/dvH6yYihHPtOub9e8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
