//go:build go1.22

// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CaseState.
const (
	NotInstrumented CaseState = "not-instrumented"
	Reviewed        CaseState = "reviewed"
	ToFix           CaseState = "to-fix"
	ToReview        CaseState = "to-review"
)

// Valid indicates whether the value is a known member of the CaseState enum.
func (e CaseState) Valid() bool {
	switch e {
	case NotInstrumented:
		return true
	case Reviewed:
		return true
	case ToFix:
		return true
	case ToReview:
		return true
	default:
		return false
	}
}

// Defines values for NewProjectIntakePolicy.
const (
	NewProjectIntakePolicyPerCase NewProjectIntakePolicy = "per-case"
	NewProjectIntakePolicyStrict  NewProjectIntakePolicy = "strict"
)

// Valid indicates whether the value is a known member of the NewProjectIntakePolicy enum.
func (e NewProjectIntakePolicy) Valid() bool {
	switch e {
	case NewProjectIntakePolicyPerCase:
		return true
	case NewProjectIntakePolicyStrict:
		return true
	default:
		return false
	}
}

// Defines values for ProjectIntakePolicy.
const (
	ProjectIntakePolicyPerCase ProjectIntakePolicy = "per-case"
	ProjectIntakePolicyStrict  ProjectIntakePolicy = "strict"
)

// Valid indicates whether the value is a known member of the ProjectIntakePolicy enum.
func (e ProjectIntakePolicy) Valid() bool {
	switch e {
	case ProjectIntakePolicyPerCase:
		return true
	case ProjectIntakePolicyStrict:
		return true
	default:
		return false
	}
}

// Defines values for GetHealth200JSONResponseBodyStatus.
const (
	Ok GetHealth200JSONResponseBodyStatus = "ok"
)

// Valid indicates whether the value is a known member of the GetHealth200JSONResponseBodyStatus enum.
func (e GetHealth200JSONResponseBodyStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Case defines model for Case.
type Case struct {
	// Archived An archived case leaves the catalogue but stays readable.
	Archived    bool      `json:"archived"`
	CategoryId  *string   `json:"categoryId,omitempty"`
	CreatedAt   time.Time `json:"createdAt"`
	Description *string   `json:"description,omitempty"`

	// Id Generated by the server when the case was created. Stable forever.
	Id        string `json:"id"`
	ProjectId string `json:"projectId"`

	// State Who holds the ball. Computed by the server from the case's comments; no
	// endpoint accepts it as an argument.
	State     CaseState `json:"state"`
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// CaseState Who holds the ball. Computed by the server from the case's comments; no
// endpoint accepts it as an argument.
type CaseState string

// CaseUpdate defines model for CaseUpdate.
type CaseUpdate struct {
	CategoryId  *string `json:"categoryId,omitempty"`
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// Category defines model for Category.
type Category struct {
	Id       string  `json:"id"`
	Name     string  `json:"name"`
	ParentId *string `json:"parentId,omitempty"`
	Position int     `json:"position"`
}

// EditionAccepted defines model for EditionAccepted.
type EditionAccepted struct {
	Captures   int    `json:"captures"`
	Cases      int    `json:"cases"`
	EditionId  string `json:"editionId"`
	Recordings int    `json:"recordings"`
}

// Grid defines model for Grid.
type Grid struct {
	CaseId string `json:"caseId"`

	// EditionId Absent when the project has taken nothing in yet.
	EditionId  *string         `json:"editionId,omitempty"`
	Recordings []GridRecording `json:"recordings"`

	// Revision What the client declared this edition was built from. Displayed, never
	// computed on.
	Revision *string    `json:"revision,omitempty"`
	Steps    []GridStep `json:"steps"`
	TakenAt  *time.Time `json:"takenAt,omitempty"`

	// Variants The variants present in this edition, in label order.
	Variants []GridVariant `json:"variants"`
}

// GridCell defines model for GridCell.
type GridCell struct {
	// Hash Fetch the image at `/blobs/{hash}`.
	Hash string `json:"hash"`

	// Provenance Where the capture was produced. Byte comparison only means something within
	// one environment, so this is recorded and never guessed.
	Provenance *Provenance `json:"provenance,omitempty"`
	VariantId  string      `json:"variantId"`
}

// GridRecording defines model for GridRecording.
type GridRecording struct {
	Hash      string `json:"hash"`
	VariantId string `json:"variantId"`
}

// GridStep defines model for GridStep.
type GridStep struct {
	// Cells One entry per variant that has a capture at this step.
	Cells    []GridCell `json:"cells"`
	Id       string     `json:"id"`
	Name     string     `json:"name"`
	Position int        `json:"position"`
}

// GridVariant defines model for GridVariant.
type GridVariant struct {
	Id string `json:"id"`

	// Label A readable rendering of the combination, such as `dark·mobile`.
	Label  string            `json:"label"`
	Values map[string]string `json:"values"`
}

// IntakeRefused defines model for IntakeRefused.
type IntakeRefused struct {
	// Detail An explanation specific to this occurrence.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`

	// MissingContent The addresses to upload before pushing again.
	MissingContent *[]string `json:"missingContent,omitempty"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title A short, human-readable summary, stable for a given type.
	Title string `json:"title"`

	// Type A URI identifying the problem type.
	//
	// Examples: https://ozalid.dev/problems/case-not-found
	Type string `json:"type"`
}

// Manifest defines model for Manifest.
type Manifest struct {
	Cases []ManifestCase `json:"cases"`

	// Revision Opaque to ozalid: displayed, never computed on. A commit hash, a build
	// number — whatever the client means by "which version produced this".
	Revision *string `json:"revision,omitempty"`
}

// ManifestCapture defines model for ManifestCapture.
type ManifestCapture struct {
	Hash string `json:"hash"`

	// Provenance Where the capture was produced. Byte comparison only means something within
	// one environment, so this is recorded and never guessed.
	Provenance *Provenance `json:"provenance,omitempty"`

	// Variant A combination of axis values, such as `{"theme":"dark","viewport":"mobile"}`.
	// The project declares its own axes — ozalid ships no list. An axis the client
	// does not supply is simply absent: a site with no theme has no theme.
	//
	//
	// Examples: {"locale":"fr","theme":"dark","viewport":"mobile"}, {"locale":"en"}
	Variant Variant `json:"variant"`
}

// ManifestCase defines model for ManifestCase.
type ManifestCase struct {
	// Id The id ozalid generated when the case was created.
	Id string `json:"id"`

	// Recordings The flow video per variant. Optional, and never compared byte-wise.
	Recordings *[]ManifestRecording `json:"recordings,omitempty"`
	Steps      []ManifestStep       `json:"steps"`
}

// ManifestRecording defines model for ManifestRecording.
type ManifestRecording struct {
	Hash string `json:"hash"`

	// Variant A combination of axis values, such as `{"theme":"dark","viewport":"mobile"}`.
	// The project declares its own axes — ozalid ships no list. An axis the client
	// does not supply is simply absent: a site with no theme has no theme.
	//
	//
	// Examples: {"locale":"fr","theme":"dark","viewport":"mobile"}, {"locale":"en"}
	Variant Variant `json:"variant"`
}

// ManifestStep defines model for ManifestStep.
type ManifestStep struct {
	Captures []ManifestCapture `json:"captures"`
	Name     string            `json:"name"`
}

// NewCase defines model for NewCase.
type NewCase struct {
	CategoryId  *string `json:"categoryId,omitempty"`
	Description *string `json:"description,omitempty"`
	Title       string  `json:"title"`
}

// NewCategory defines model for NewCategory.
type NewCategory struct {
	Name     string  `json:"name"`
	ParentId *string `json:"parentId,omitempty"`
	Position *int    `json:"position,omitempty"`
}

// NewProject defines model for NewProject.
type NewProject struct {
	IntakePolicy *NewProjectIntakePolicy `json:"intakePolicy,omitempty"`
	Name         string                  `json:"name"`
	Slug         string                  `json:"slug"`
}

// NewProjectIntakePolicy defines model for NewProject.IntakePolicy.
type NewProjectIntakePolicy string

// Project defines model for Project.
type Project struct {
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`

	// IntakePolicy `strict` refuses intake while any case is to-review; `per-case` never
	// refuses.
	IntakePolicy ProjectIntakePolicy `json:"intakePolicy"`
	Name         string              `json:"name"`
	Slug         string              `json:"slug"`
}

// ProjectIntakePolicy `strict` refuses intake while any case is to-review; `per-case` never
// refuses.
type ProjectIntakePolicy string

// Provenance Where the capture was produced. Byte comparison only means something within
// one environment, so this is recorded and never guessed.
type Provenance struct {
	Browser        *string `json:"browser,omitempty"`
	BrowserVersion *string `json:"browserVersion,omitempty"`
	EnvironmentId  *string `json:"environmentId,omitempty"`
	Os             *string `json:"os,omitempty"`

	// Resolution The effective resolution, recorded as provenance and never as identity.
	Resolution *string `json:"resolution,omitempty"`
}

// Variant A combination of axis values, such as `{"theme":"dark","viewport":"mobile"}`.
// The project declares its own axes — ozalid ships no list. An axis the client
// does not supply is simply absent: a site with no theme has no theme.
//
// Examples: {"locale":"fr","theme":"dark","viewport":"mobile"}, {"locale":"en"}
type Variant map[string]string

// Problem defines model for problem.
type Problem struct {
	// Detail An explanation specific to this occurrence.
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`

	// Status The HTTP status code.
	Status int `json:"status"`

	// Title A short, human-readable summary, stable for a given type.
	Title string `json:"title"`

	// Type A URI identifying the problem type.
	//
	// Examples: https://ozalid.dev/problems/case-not-found
	Type string `json:"type"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Problem

// NotFound defines model for NotFound.
type NotFound = Problem

// GetCaseCapturesParams defines parameters for GetCaseCaptures.
type GetCaseCapturesParams struct {
	EditionId *string `form:"editionId,omitempty" json:"editionId,omitempty"`
}

// GetHealth200JSONResponseBodyStatus defines parameters for GetHealth.
type GetHealth200JSONResponseBodyStatus string

// ListCasesParams defines parameters for ListCases.
type ListCasesParams struct {
	State      *CaseState `form:"state,omitempty" json:"state,omitempty"`
	CategoryId *string    `form:"categoryId,omitempty" json:"categoryId,omitempty"`
}

// UpdateCaseJSONRequestBody defines body for UpdateCase for application/json ContentType.
type UpdateCaseJSONRequestBody = CaseUpdate

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = NewProject

// CreateCaseJSONRequestBody defines body for CreateCase for application/json ContentType.
type CreateCaseJSONRequestBody = NewCase

// CreateCategoryJSONRequestBody defines body for CreateCategory for application/json ContentType.
type CreateCategoryJSONRequestBody = NewCategory

// CreateEditionJSONRequestBody defines body for CreateEdition for application/json ContentType.
type CreateEditionJSONRequestBody = Manifest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// GetBlob Download the content at this address
	// (GET /blobs/{hash})
	GetBlob(w http.ResponseWriter, r *http.Request, hash string)
	// HeadBlob Report whether the store already holds this content
	// (HEAD /blobs/{hash})
	HeadBlob(w http.ResponseWriter, r *http.Request, hash string)
	// PutBlob Store content under its address
	// (PUT /blobs/{hash})
	PutBlob(w http.ResponseWriter, r *http.Request, hash string)
	// GetCase Read a case, archived or not
	// (GET /cases/{caseId})
	GetCase(w http.ResponseWriter, r *http.Request, caseId string)
	// UpdateCase Change what is mutable about a case
	// (PATCH /cases/{caseId})
	UpdateCase(w http.ResponseWriter, r *http.Request, caseId string)
	// ArchiveCase Take a case out of the catalogue
	// (POST /cases/{caseId}/archive)
	ArchiveCase(w http.ResponseWriter, r *http.Request, caseId string)
	// GetCaseCaptures Read the evidence a case is judged from
	// (GET /cases/{caseId}/captures)
	GetCaseCaptures(w http.ResponseWriter, r *http.Request, caseId string, params GetCaseCapturesParams)
	// DeleteCategory Remove an empty node
	// (DELETE /categories/{categoryId})
	DeleteCategory(w http.ResponseWriter, r *http.Request, categoryId string)
	// GetHealth Report whether the service is able to serve
	// (GET /health)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// CreateProject Open a book
	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)
	// GetProject Read a project
	// (GET /projects/{slug})
	GetProject(w http.ResponseWriter, r *http.Request, slug string)
	// ListCases List the catalogue
	// (GET /projects/{slug}/cases)
	ListCases(w http.ResponseWriter, r *http.Request, slug string, params ListCasesParams)
	// CreateCase Open a case and receive its id
	// (POST /projects/{slug}/cases)
	CreateCase(w http.ResponseWriter, r *http.Request, slug string)
	// ListCategories Read the catalogue tree
	// (GET /projects/{slug}/categories)
	ListCategories(w http.ResponseWriter, r *http.Request, slug string)
	// CreateCategory Add a node to the tree
	// (POST /projects/{slug}/categories)
	CreateCategory(w http.ResponseWriter, r *http.Request, slug string)
	// CreateEdition Take a run's evidence into the book
	// (POST /projects/{slug}/editions)
	CreateEdition(w http.ResponseWriter, r *http.Request, slug string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBlob operation middleware
func (siw *ServerInterfaceWrapper) GetBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HeadBlob operation middleware
func (siw *ServerInterfaceWrapper) HeadBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HeadBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutBlob operation middleware
func (siw *ServerInterfaceWrapper) PutBlob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "hash" -------------
	var hash string

	err = runtime.BindStyledParameterWithOptions("simple", "hash", r.PathValue("hash"), &hash, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "hash", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutBlob(w, r, hash)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCase operation middleware
func (siw *ServerInterfaceWrapper) GetCase(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "caseId" -------------
	var caseId string

	err = runtime.BindStyledParameterWithOptions("simple", "caseId", r.PathValue("caseId"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "caseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCase(w, r, caseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCase operation middleware
func (siw *ServerInterfaceWrapper) UpdateCase(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "caseId" -------------
	var caseId string

	err = runtime.BindStyledParameterWithOptions("simple", "caseId", r.PathValue("caseId"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "caseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCase(w, r, caseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ArchiveCase operation middleware
func (siw *ServerInterfaceWrapper) ArchiveCase(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "caseId" -------------
	var caseId string

	err = runtime.BindStyledParameterWithOptions("simple", "caseId", r.PathValue("caseId"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "caseId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ArchiveCase(w, r, caseId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCaseCaptures operation middleware
func (siw *ServerInterfaceWrapper) GetCaseCaptures(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "caseId" -------------
	var caseId string

	err = runtime.BindStyledParameterWithOptions("simple", "caseId", r.PathValue("caseId"), &caseId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "caseId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetCaseCapturesParams

	// ------------- Optional query parameter "editionId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "editionId", r.URL.Query(), &params.EditionId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "editionId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "editionId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCaseCaptures(w, r, caseId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteCategory operation middleware
func (siw *ServerInterfaceWrapper) DeleteCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "categoryId" -------------
	var categoryId string

	err = runtime.BindStyledParameterWithOptions("simple", "categoryId", r.PathValue("categoryId"), &categoryId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteCategory(w, r, categoryId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCases operation middleware
func (siw *ServerInterfaceWrapper) ListCases(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCasesParams

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "categoryId" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "categoryId", r.URL.Query(), &params.CategoryId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "categoryId"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "categoryId", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCases(w, r, slug, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCase operation middleware
func (siw *ServerInterfaceWrapper) CreateCase(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCase(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCategories operation middleware
func (siw *ServerInterfaceWrapper) ListCategories(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCategories(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateCategory operation middleware
func (siw *ServerInterfaceWrapper) CreateCategory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCategory(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEdition operation middleware
func (siw *ServerInterfaceWrapper) CreateEdition(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "slug" -------------
	var slug string

	err = runtime.BindStyledParameterWithOptions("simple", "slug", r.PathValue("slug"), &slug, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "slug", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEdition(w, r, slug)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/health", wrapper.GetHealth)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/blobs/{hash}", wrapper.GetBlob)
	m.HandleFunc(http.MethodHead+" "+options.BaseURL+"/blobs/{hash}", wrapper.HeadBlob)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/blobs/{hash}", wrapper.PutBlob)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{slug}", wrapper.GetProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{slug}/cases", wrapper.ListCases)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{slug}/cases", wrapper.CreateCase)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{slug}/editions", wrapper.CreateEdition)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{slug}/categories", wrapper.ListCategories)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{slug}/categories", wrapper.CreateCategory)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cases/{caseId}", wrapper.GetCase)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/cases/{caseId}", wrapper.UpdateCase)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/cases/{caseId}/captures", wrapper.GetCaseCaptures)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/cases/{caseId}/archive", wrapper.ArchiveCase)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/categories/{categoryId}", wrapper.DeleteCategory)

	return m
}

type BadRequestApplicationProblemPlusJSONResponse Problem

type NotFoundApplicationProblemPlusJSONResponse Problem

type GetBlobRequestObject struct {
	Hash string `json:"hash"`
}

type GetBlobResponseObject interface {
	VisitGetBlobResponse(w http.ResponseWriter) error
}

type GetBlob200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetBlob200ApplicationoctetStreamResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response GetBlob400ApplicationProblemPlusJSONResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetBlob404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetBlob404ApplicationProblemPlusJSONResponse) VisitGetBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type HeadBlobRequestObject struct {
	Hash string `json:"hash"`
}

type HeadBlobResponseObject interface {
	VisitHeadBlobResponse(w http.ResponseWriter) error
}

type HeadBlob200Response struct {
}

func (response HeadBlob200Response) VisitHeadBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type HeadBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response HeadBlob400ApplicationProblemPlusJSONResponse) VisitHeadBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type HeadBlob404Response struct {
}

func (response HeadBlob404Response) VisitHeadBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(404)
	return nil
}

type PutBlobRequestObject struct {
	Hash string `json:"hash"`
	Body io.Reader
}

type PutBlobResponseObject interface {
	VisitPutBlobResponse(w http.ResponseWriter) error
}

type PutBlob201Response struct {
}

func (response PutBlob201Response) VisitPutBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(201)
	return nil
}

type PutBlob204Response struct {
}

func (response PutBlob204Response) VisitPutBlobResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type PutBlob400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response PutBlob400ApplicationProblemPlusJSONResponse) VisitPutBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PutBlob422ApplicationProblemPlusJSONResponse Problem

func (response PutBlob422ApplicationProblemPlusJSONResponse) VisitPutBlobResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetCaseRequestObject struct {
	CaseId string `json:"caseId"`
}

type GetCaseResponseObject interface {
	VisitGetCaseResponse(w http.ResponseWriter) error
}

type GetCase200JSONResponse Case

func (response GetCase200JSONResponse) VisitGetCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCase404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetCase404ApplicationProblemPlusJSONResponse) VisitGetCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCaseRequestObject struct {
	CaseId string `json:"caseId"`
	Body   *UpdateCaseJSONRequestBody
}

type UpdateCaseResponseObject interface {
	VisitUpdateCaseResponse(w http.ResponseWriter) error
}

type UpdateCase200JSONResponse Case

func (response UpdateCase200JSONResponse) VisitUpdateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCase400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response UpdateCase400ApplicationProblemPlusJSONResponse) VisitUpdateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateCase404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response UpdateCase404ApplicationProblemPlusJSONResponse) VisitUpdateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCaseRequestObject struct {
	CaseId string `json:"caseId"`
}

type ArchiveCaseResponseObject interface {
	VisitArchiveCaseResponse(w http.ResponseWriter) error
}

type ArchiveCase204Response struct {
}

func (response ArchiveCase204Response) VisitArchiveCaseResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type ArchiveCase404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ArchiveCase404ApplicationProblemPlusJSONResponse) VisitArchiveCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ArchiveCase409ApplicationProblemPlusJSONResponse Problem

func (response ArchiveCase409ApplicationProblemPlusJSONResponse) VisitArchiveCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetCaseCapturesRequestObject struct {
	CaseId string `json:"caseId"`
	Params GetCaseCapturesParams
}

type GetCaseCapturesResponseObject interface {
	VisitGetCaseCapturesResponse(w http.ResponseWriter) error
}

type GetCaseCaptures200JSONResponse Grid

func (response GetCaseCaptures200JSONResponse) VisitGetCaseCapturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetCaseCaptures404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetCaseCaptures404ApplicationProblemPlusJSONResponse) VisitGetCaseCapturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCategoryRequestObject struct {
	CategoryId string `json:"categoryId"`
}

type DeleteCategoryResponseObject interface {
	VisitDeleteCategoryResponse(w http.ResponseWriter) error
}

type DeleteCategory204Response struct {
}

func (response DeleteCategory204Response) VisitDeleteCategoryResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteCategory404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response DeleteCategory404ApplicationProblemPlusJSONResponse) VisitDeleteCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteCategory409ApplicationProblemPlusJSONResponse Problem

func (response DeleteCategory409ApplicationProblemPlusJSONResponse) VisitDeleteCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200JSONResponse struct {
	Status GetHealth200JSONResponseBodyStatus `json:"status"`

	// Version The build this instance runs.
	//
	// Examples: 0.1.0
	Version string `json:"version"`
}

func (response GetHealth200JSONResponse) VisitGetHealthResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProjectRequestObject struct {
	Body *CreateProjectJSONRequestBody
}

type CreateProjectResponseObject interface {
	VisitCreateProjectResponse(w http.ResponseWriter) error
}

type CreateProject201JSONResponse Project

func (response CreateProject201JSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProject400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateProject400ApplicationProblemPlusJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateProject409ApplicationProblemPlusJSONResponse Problem

func (response CreateProject409ApplicationProblemPlusJSONResponse) VisitCreateProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type GetProjectRequestObject struct {
	Slug string `json:"slug"`
}

type GetProjectResponseObject interface {
	VisitGetProjectResponse(w http.ResponseWriter) error
}

type GetProject200JSONResponse Project

func (response GetProject200JSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetProject404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response GetProject404ApplicationProblemPlusJSONResponse) VisitGetProjectResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListCasesRequestObject struct {
	Slug   string `json:"slug"`
	Params ListCasesParams
}

type ListCasesResponseObject interface {
	VisitListCasesResponse(w http.ResponseWriter) error
}

type ListCases200JSONResponse []Case

func (response ListCases200JSONResponse) VisitListCasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCases404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListCases404ApplicationProblemPlusJSONResponse) VisitListCasesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCaseRequestObject struct {
	Slug string `json:"slug"`
	Body *CreateCaseJSONRequestBody
}

type CreateCaseResponseObject interface {
	VisitCreateCaseResponse(w http.ResponseWriter) error
}

type CreateCase201JSONResponse Case

func (response CreateCase201JSONResponse) VisitCreateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCase400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateCase400ApplicationProblemPlusJSONResponse) VisitCreateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCase404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateCase404ApplicationProblemPlusJSONResponse) VisitCreateCaseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategoriesRequestObject struct {
	Slug string `json:"slug"`
}

type ListCategoriesResponseObject interface {
	VisitListCategoriesResponse(w http.ResponseWriter) error
}

type ListCategories200JSONResponse []Category

func (response ListCategories200JSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListCategories404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response ListCategories404ApplicationProblemPlusJSONResponse) VisitListCategoriesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategoryRequestObject struct {
	Slug string `json:"slug"`
	Body *CreateCategoryJSONRequestBody
}

type CreateCategoryResponseObject interface {
	VisitCreateCategoryResponse(w http.ResponseWriter) error
}

type CreateCategory201JSONResponse Category

func (response CreateCategory201JSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateCategory400ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateCategory404ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateCategory409ApplicationProblemPlusJSONResponse Problem

func (response CreateCategory409ApplicationProblemPlusJSONResponse) VisitCreateCategoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEditionRequestObject struct {
	Slug string `json:"slug"`
	Body *CreateEditionJSONRequestBody
}

type CreateEditionResponseObject interface {
	VisitCreateEditionResponse(w http.ResponseWriter) error
}

type CreateEdition201JSONResponse EditionAccepted

func (response CreateEdition201JSONResponse) VisitCreateEditionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdition400ApplicationProblemPlusJSONResponse struct {
	BadRequestApplicationProblemPlusJSONResponse
}

func (response CreateEdition400ApplicationProblemPlusJSONResponse) VisitCreateEditionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdition404ApplicationProblemPlusJSONResponse struct {
	NotFoundApplicationProblemPlusJSONResponse
}

func (response CreateEdition404ApplicationProblemPlusJSONResponse) VisitCreateEditionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type CreateEdition409ApplicationProblemPlusJSONResponse IntakeRefused

func (response CreateEdition409ApplicationProblemPlusJSONResponse) VisitCreateEditionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// GetBlob Download the content at this address
	// (GET /blobs/{hash})
	GetBlob(ctx context.Context, request GetBlobRequestObject) (GetBlobResponseObject, error)
	// HeadBlob Report whether the store already holds this content
	// (HEAD /blobs/{hash})
	HeadBlob(ctx context.Context, request HeadBlobRequestObject) (HeadBlobResponseObject, error)
	// PutBlob Store content under its address
	// (PUT /blobs/{hash})
	PutBlob(ctx context.Context, request PutBlobRequestObject) (PutBlobResponseObject, error)
	// GetCase Read a case, archived or not
	// (GET /cases/{caseId})
	GetCase(ctx context.Context, request GetCaseRequestObject) (GetCaseResponseObject, error)
	// UpdateCase Change what is mutable about a case
	// (PATCH /cases/{caseId})
	UpdateCase(ctx context.Context, request UpdateCaseRequestObject) (UpdateCaseResponseObject, error)
	// ArchiveCase Take a case out of the catalogue
	// (POST /cases/{caseId}/archive)
	ArchiveCase(ctx context.Context, request ArchiveCaseRequestObject) (ArchiveCaseResponseObject, error)
	// GetCaseCaptures Read the evidence a case is judged from
	// (GET /cases/{caseId}/captures)
	GetCaseCaptures(ctx context.Context, request GetCaseCapturesRequestObject) (GetCaseCapturesResponseObject, error)
	// DeleteCategory Remove an empty node
	// (DELETE /categories/{categoryId})
	DeleteCategory(ctx context.Context, request DeleteCategoryRequestObject) (DeleteCategoryResponseObject, error)
	// GetHealth Report whether the service is able to serve
	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// CreateProject Open a book
	// (POST /projects)
	CreateProject(ctx context.Context, request CreateProjectRequestObject) (CreateProjectResponseObject, error)
	// GetProject Read a project
	// (GET /projects/{slug})
	GetProject(ctx context.Context, request GetProjectRequestObject) (GetProjectResponseObject, error)
	// ListCases List the catalogue
	// (GET /projects/{slug}/cases)
	ListCases(ctx context.Context, request ListCasesRequestObject) (ListCasesResponseObject, error)
	// CreateCase Open a case and receive its id
	// (POST /projects/{slug}/cases)
	CreateCase(ctx context.Context, request CreateCaseRequestObject) (CreateCaseResponseObject, error)
	// ListCategories Read the catalogue tree
	// (GET /projects/{slug}/categories)
	ListCategories(ctx context.Context, request ListCategoriesRequestObject) (ListCategoriesResponseObject, error)
	// CreateCategory Add a node to the tree
	// (POST /projects/{slug}/categories)
	CreateCategory(ctx context.Context, request CreateCategoryRequestObject) (CreateCategoryResponseObject, error)
	// CreateEdition Take a run's evidence into the book
	// (POST /projects/{slug}/editions)
	CreateEdition(ctx context.Context, request CreateEditionRequestObject) (CreateEditionResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// GetBlob operation middleware
func (sh *strictHandler) GetBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request GetBlobRequestObject

	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetBlob(ctx, request.(GetBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetBlobResponseObject); ok {
		if err := validResponse.VisitGetBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// HeadBlob operation middleware
func (sh *strictHandler) HeadBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request HeadBlobRequestObject

	request.Hash = hash

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.HeadBlob(ctx, request.(HeadBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "HeadBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HeadBlobResponseObject); ok {
		if err := validResponse.VisitHeadBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PutBlob operation middleware
func (sh *strictHandler) PutBlob(w http.ResponseWriter, r *http.Request, hash string) {
	var request PutBlobRequestObject

	request.Hash = hash

	request.Body = r.Body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PutBlob(ctx, request.(PutBlobRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PutBlob")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PutBlobResponseObject); ok {
		if err := validResponse.VisitPutBlobResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCase operation middleware
func (sh *strictHandler) GetCase(w http.ResponseWriter, r *http.Request, caseId string) {
	var request GetCaseRequestObject

	request.CaseId = caseId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCase(ctx, request.(GetCaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCaseResponseObject); ok {
		if err := validResponse.VisitGetCaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateCase operation middleware
func (sh *strictHandler) UpdateCase(w http.ResponseWriter, r *http.Request, caseId string) {
	var request UpdateCaseRequestObject

	request.CaseId = caseId

	var body UpdateCaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateCase(ctx, request.(UpdateCaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateCase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateCaseResponseObject); ok {
		if err := validResponse.VisitUpdateCaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ArchiveCase operation middleware
func (sh *strictHandler) ArchiveCase(w http.ResponseWriter, r *http.Request, caseId string) {
	var request ArchiveCaseRequestObject

	request.CaseId = caseId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ArchiveCase(ctx, request.(ArchiveCaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ArchiveCase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ArchiveCaseResponseObject); ok {
		if err := validResponse.VisitArchiveCaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCaseCaptures operation middleware
func (sh *strictHandler) GetCaseCaptures(w http.ResponseWriter, r *http.Request, caseId string, params GetCaseCapturesParams) {
	var request GetCaseCapturesRequestObject

	request.CaseId = caseId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCaseCaptures(ctx, request.(GetCaseCapturesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCaseCaptures")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetCaseCapturesResponseObject); ok {
		if err := validResponse.VisitGetCaseCapturesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteCategory operation middleware
func (sh *strictHandler) DeleteCategory(w http.ResponseWriter, r *http.Request, categoryId string) {
	var request DeleteCategoryRequestObject

	request.CategoryId = categoryId

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteCategory(ctx, request.(DeleteCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteCategoryResponseObject); ok {
		if err := validResponse.VisitDeleteCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(w http.ResponseWriter, r *http.Request) {
	var request GetHealthRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx, request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		if err := validResponse.VisitGetHealthResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateProject operation middleware
func (sh *strictHandler) CreateProject(w http.ResponseWriter, r *http.Request) {
	var request CreateProjectRequestObject

	var body CreateProjectJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateProject(ctx, request.(CreateProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateProjectResponseObject); ok {
		if err := validResponse.VisitCreateProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetProject operation middleware
func (sh *strictHandler) GetProject(w http.ResponseWriter, r *http.Request, slug string) {
	var request GetProjectRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetProject(ctx, request.(GetProjectRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetProject")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetProjectResponseObject); ok {
		if err := validResponse.VisitGetProjectResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCases operation middleware
func (sh *strictHandler) ListCases(w http.ResponseWriter, r *http.Request, slug string, params ListCasesParams) {
	var request ListCasesRequestObject

	request.Slug = slug
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCases(ctx, request.(ListCasesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCases")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCasesResponseObject); ok {
		if err := validResponse.VisitListCasesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCase operation middleware
func (sh *strictHandler) CreateCase(w http.ResponseWriter, r *http.Request, slug string) {
	var request CreateCaseRequestObject

	request.Slug = slug

	var body CreateCaseJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCase(ctx, request.(CreateCaseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCase")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCaseResponseObject); ok {
		if err := validResponse.VisitCreateCaseResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListCategories operation middleware
func (sh *strictHandler) ListCategories(w http.ResponseWriter, r *http.Request, slug string) {
	var request ListCategoriesRequestObject

	request.Slug = slug

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListCategories(ctx, request.(ListCategoriesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListCategories")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListCategoriesResponseObject); ok {
		if err := validResponse.VisitListCategoriesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateCategory operation middleware
func (sh *strictHandler) CreateCategory(w http.ResponseWriter, r *http.Request, slug string) {
	var request CreateCategoryRequestObject

	request.Slug = slug

	var body CreateCategoryJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCategory(ctx, request.(CreateCategoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCategory")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateCategoryResponseObject); ok {
		if err := validResponse.VisitCreateCategoryResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateEdition operation middleware
func (sh *strictHandler) CreateEdition(w http.ResponseWriter, r *http.Request, slug string) {
	var request CreateEditionRequestObject

	request.Slug = slug

	var body CreateEditionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateEdition(ctx, request.(CreateEditionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateEdition")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateEditionResponseObject); ok {
		if err := validResponse.VisitCreateEditionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fzvjts4kn+Vgm6BAebU7j+b5BLPp55kZybA7iTIZHc/xH1oWipbnKZIDUnZ8TYM3EPcu9z3e5R7kkMV",
	"KVm26W73JN2L/RS1JZFVxapf/VVus8LUjdGovcvGt5lF1xjtkP/4XpQf8LcWnae/CqM9ar4UTaNkIbw0",
	"+rSxZqqw/vdfndF0zxUV1oKu/mBxlo2zfzvdbHEa7rrurWy9XudZia6wsqHlsnH2sUKwYVuQDmqhZsbW",
	"WI6ydZ79bPwPptXlUxL0swHXFhVYdKa1BY4yeia+SOu+Fg7p38aaBq2XQXrCFpVcIJO6veClhu4mFMIh",
	"KBQLdOArhEJ4ocy8RZi2HpwXKwcWRSmmCkdZnvlVg9k4mxqjUGgSSSE8zo1dveWddKsUPZuNvW2xf955",
	"K/WcH7coPJaXLDeSrPDZOCuFxxMva8wSr2xRf8QWMsHzj6jR0sYwXTGjDu0CLSwr1JFxh7AUDiKBI/jF",
	"0y4wMxYXaEcpyhprfsXCB9b37jovPN538HR4v/CD6zzz0itMrtU25cPEts4z0mJpSQM+kUyG5HZbdUTm",
	"G3UZHtFw36t+CzOlVYiqDfF7Av97ZaAyqgxqNRVKjeC1qZt2/wxm1tT9GXzjoDB1TTL6DrSZaNRlY6T2",
	"IIoCG+9AehAOBCnxvKUHRxOd5RnqtiZOtfEnUjtv+R4z5M2JxYXEZbieyc8ZSYd+wXLA2EbcxNhfmfV9",
	"w3qgwj9Ue3sdqKX+M+q5r7Lx+X3HG15KH1Ggdp8PmdZaLeq0CjbCovZHct0YJzuW402pPc7RplWTdx28",
	"lmLlTyXfu2Q9CMC2ezKNb2243t2UgModuoVh5QN2bLEwtpR67o7gZrNUt2O+oWtrrRSLP1qZ5MvhAdq2",
	"KN+B+alD7TcIF60fKuHAixvUoI2vpJ6D1LBCn0S4bd6lx9rdh2jEw4fuNdbosKiwVqzCmgvpom7sgobw",
	"AQmUJNpLLJSwWIKvpIPIK6P0tJXKM3KM4I10jRIrLHPQBNUTXXRAY3QAhwQ2Y/Mwln7x2KS4YVE+xJ0t",
	"hJUixjv7oUd3FxqLfH5Sb3Gf0w9KTFGBsWXwS0fz8Lew+D4bO0ocFW5AayexozT4NSq1r8WVcNU+zz+g",
	"Lyo+c1mLOYLwcH06VWbqTm/pjfX1Ic+7QC10ca+Dfb95ciP8pDXtCGHzaB5oP8TuRtkP8nxICb4qHayh",
	"++CBSiV07Z1GQO3tChq0ndaBJwMkgBAQQQvYIqUDOv8HKRtrQcJgHux3vtCV5FEEh8TWGcWxDpKNLwG3",
	"fZwMFnWJ9DiYWYAzU0+lFsF+OZgXDq5LYW/+939qM5UK01q+EKqN0XwZzF+o91s07ocP2yymBBQY6FdP",
	"yeWtJlj7gLPWBUcrlHo3y8afjsxi8l1Z1tI5qeevNznTPvSJsrToHGUiBtpGGVHCFCn+hqZ17KnEXEi9",
	"pYWHBLABth3mrtZ59heh5Szmlfuu9ni/0K3DGdg6p5DtbXjv/CFu710jfmuRuDb/EEqWYyh3XBoMPRpc",
	"cogs2VKrHAR7w3KidVtP0cL//dd/w7ISnl8ceNMahXYUe0+yZSWLChZoiSCKDMq2iG52kiVdZsJDpFVn",
	"IxPGj8OY2Ajv0RL//+kqcfH8xfjT2ckrcTK7un3xbP2HR0D9+17q3WMage/C3y1NOIAk+xovy3jiMO/z",
	"08MZ6f3x2f4OM2WWsJAlmiHOj+BdE9AkB6HLgY5xtDVdeTxZSodH433H/p1x38Nirm7JdNyVwrWw/l2n",
	"c4Sn/h1a+XTadcDDD9KeB8JWMNHEWXXe+CFJaHS8PTkpTn7GZdpEtrPq+7Lox86amcxDifNRstnOl+8M",
	"akqciVb5bHyW3xfg8NYHCH4f8rsE+rAzf2+ULFZb+2UN2hOCmUH5hEgsSBn7e6n6yJEicKqd7xjVJ3Hy",
	"j7OTV1fx35Or2/P8xUXKsHZY57XywxI4yP7vqDgeiPz2BTmE2+sgumuwHDY5CI/DspIKQehVQHRJ4U2s",
	"R30H152Yr7vcNb69XdR62KkcPIcjaoRDMe9wPKwMHjiBgXfezezRYnRrIa8gz9YFHiP4fuUxOiDpjAaj",
	"1SoGLM7UGOoUS0n/TrTh3GUhrdE1ap+DMyFHkQ6CQ8Ry4NfmLUWVZZDotm5MrVk6tEmhxXt/C0FSuvqy",
	"IeKAnRt3oKTkjGp9Mhokt42zGRZeLhA2T+YD3lh0UdgDToUDWaL20q9GSYPaO7NB8nN0irGb9wyyG0p4",
	"xGfpIOQWg2TndpL5CmucZONJRpnPJMsnGRlBY6znX0MmNMnW16OJ/jioWMUykAPpHZilBvEZHYe5MXpy",
	"lWwcaANKOj+CSx2I2MS+E10apCc8uLZp1IpUxcmargTXycYgwEmPrGS0FFPLuXD3RzTJz6JuFInm022m",
	"TCHI72QzS/Kmpxhb7A3lV5G5bBxZ47yofwV1tk6ZUZdE7QFZiV5Ilezn4OdGiXgErsFCzmRB+QRbhSmK",
	"1lrUBSZDSKmd74y2h8fWyhOLM+TX0gU04dsDQedPHz++h/AAFKYcbjsouvYue1efXGWsz6Fqa6FP+qTa",
	"tXUt7CqnhWNfBgTM5YLC5VWT5i38sL/FXz+8jZYyWxGyxPooyb1fbHDQWeV948anp0HfRiUuulzXnRIc",
	"n2jjT2bcGbzKt6R4r1/ju9v9mDYVO635qGYmxU5lHKUOwanA1JgbFg/q8sSbE9QleHQekBKBTg2C9LPA",
	"EWlrh3PZ2eh8dMbg1aAWjczG2R/5J4ppfMWHvlWiox/myCBC+iq6inT2I/rvlZly1XDQ2L04O7ujgWoK",
	"j/7EeYui3m6g9nIluLGrhGiT3dy4Dzdwn4WtU9FxT+LpoPHMrzy7/5W+Mcy92aCq2Th7Y5aa6xh+Q0df",
	"UYv1DmJDzFnNWKjZ1TrPKhSJnDGUZaAQSrmwRqyPONSU1nDm5sabnRSZzwoqVCUhXgwxQm2F/MhcSJ1D",
	"qAZIx1UDqMUNOhAwa5WChXStUFBJ541dgZjNjA3NYAbD7eP+CUV5x3nvnwwtin2bULqvdFSHNup9AO24",
	"u+HWuX1AAm7KxX0ViyhhiV6iezQnj7ERVtTo0QZ3cVA3O13I2VfGxPMaZkYpswwN0xfPgK4tB5EVfoai",
	"ElYUtPY2WvUJIV2yHyYLCUu+mr18UZ69PH/58lnxH+WL56/ExQyFOCuePxfl2flz8cfp7NnsfHoxPZu+",
	"vLgoyvPn5Yvi/Pn0bHZ2Js5eZgGFKHUQvurixHHIXIe4FtqCG9N9cFpNrrFpE5XCtyXWjfHssulMSO07",
	"KXL5mixrqPdFJfQ8HDxFkSMgubOhTLSwGMP1EiTXaldQGtaRGJvy2QutTasLsphwThx8dLs66b3U84kW",
	"ntvS8REmple5wMQUQXpYmlaVUFHcRga5glnLITERHbRtopfW6HmP2H1UshQr8uvaeFmQDU7037t6Ubfv",
	"Lv90L1ZT6ZZ2S7RYwvXF2bNrXte0Puw5NeUKpkgSpfcJqIRSHF6LrojYIQ2tGmhkUUKriXQBN9os9UQP",
	"iCHuvVFlEDybUdnLjhsLUikojLVY+O9ggTY6ZRbTRFMWwPRIFgjJq2NHM0gNACzArOsAdmFk6UbwWig1",
	"0dc//enyzTXMpHWeY2Z3I5sAeTsiS2Hb+3bjyhhvvjfl6vG82LYlrfcA9TyNc1tiJUEzkl7cDYs72vIV",
	"YPji4qkntoISHmO6u1D/C8ugE1xQY8ozDnvndZ5x0OdOb0Oj9M4A6HWorzwgAHqYYELv4UDkIxyOvjSG",
	"+cBQwGvlm8ExY0nUA+nEjsC+00u4i76/fNhhpNyB8EWig/zWU9bLFk3nxgNNQMDOqiCsD104wQMO28cT",
	"Rnz6EzrGrh9+OHGO6Cizfhq1iENdQ/V40qj4NXvkHnrrNmR0YkqeKGhaQrH2ze40amMIMB5J6YxLBSGe",
	"sLNx0VsqyfkXO5XwszLFTRitoYg9j7eG05TBpUvvJrqrmOf96Bs//6tprRaK/abF4EqhRIVERMpHXQZx",
	"pBHngAvoapKdYf8euKAXXj014vftsc59DTjY0raPlDIFrQJSsK4n3026HqdqwyZLhPp9muZWlmOelHAU",
	"nPCATs679WM9HBXiZ+l8UIphSXQYSKIoKihQKW73olJ9CNg9vVvB4piUMC/ESHHHiebNHAVz4QYPclDk",
	"+Cb0AVwoFPXltm8c1BRCWSxo1Th3RGT0lSWjiWgNUwThbrCc6JmxOTjJ5cgg6lqsiCEwmoJio8iv9hNc",
	"XBKXbP1dvBmmMZmwy7BCP4wSiptTRN0xX8Y41gWpCA1YN37FB5CzEISeaLTW2DH/GXYZzoWy0oPCufSy",
	"JpfBjiNlVtGJv95M8aXA5rcWOZiLaDOcA7wTYB7NA/As4QHj2VSCvkZw4AcrdscvHfzalnMseUjvCeOE",
	"YLvcu5PBgLvG4joYrcLUvPI7TYbU6ZHROII3DLV6DgJmUtFFacUSLdSt86GWLBVqr1ZQm0X0Z0vhJlpq",
	"J0tS8C53ijRw2SCs6NrpSf8zlzI7scV8NFiChm+/7YDt22/DM4Vp2UX0cfqYTCmkUaFF4GAZXAbTQ9Rj",
	"mU804Y3YHf4nB4w8+2XYQ8GyMgpH8BdiSfqYL8keNJniieYpUgNzk7IYlhz2HdTjfVGUh3QwpyP41/FF",
	"G8IZgUmJ9mtKrCW9jmlTbvueTmePNo6+Y/5gA6lQKF/dlbb8FJ74QnzabmBsegZdX9PcJBuZi03PLZHq",
	"tbLLU7vWBdhWu92afShjX93bVw5EbTZNl94TyTPahSyCH6ZLPT+mirh5iYNAMjq0i6EixEdiGBKdMkut",
	"i0W3D+s1N2W79vfj5DGD8YLjyxNfZeetbfcPoWsRSgemQf37s5knxgzhwal2zjUrccOEb6nOuwY1CG7l",
	"DFSjV4Zt3Ti9pbXurEIM1eOR4o3jTuprlSOanqGEcI6Bzzjo8EDg3BH5aT8vmswJfpCKSKAY2G9qnxxo",
	"5n3p1RVCawoKwtxm34qJ30hxOUO6iY5vh6LsCC6HXtyFggfHySEZTbnlP8swoHhkCNt9GnZ8wSF+yLbO",
	"0wtueazHC4qPmoHrRnZ3xgoPppruixWXpH9v5vk4mnuojBFnUAtTo4OpKG42c6jfDSeHWfXCl3e65BYA",
	"/2F0SCkn2rVTR2g6zBff+qiQUi+4pkERXUIrg/96xCJcN3P4xJ7rvsJs57NyMK3nfIEkPmu1RgWt9lJB",
	"GPHukl73z6jVRUfEBNPhWyxQcmbggOcGUrWTfZTsY9tDPipgU//Y00BAzE+OhAFvEXMIY519572opCpt",
	"H3l8hUx68wk2bfglGcKXAEXaRgcJ3SPZaXckT22rw30PJ3hPZIFPHpBegpNTLnF01dRCWNK0UIQjfdqN",
	"UC9LCsMoie3qh3epawoVoqdwx5Xvv57Xe9+6qvssq1HoEeo4ED+CS3cD3CiG7Y8QB23j2HxeVsJPtD8w",
	"XEKxnOjXhW6UjiUcqrWDVm2s+Ew0FzNpSYrheJZy+EkU+V2uCnEFL5ZSKVS00nvUXHHWdAxCO1HQXS4M",
	"xfovl3Xy2Lfrokheq+8tNLG337nwg846fon9SDjQf531xCCw+335odrpRvIyxPWUpf1LI8P2534H+O6V",
	"mfIVLqnHz8ilHg+1OX7qlw9Kmq2OYyGkfaLGEvxSFkEbh5+m21Y76OfouVzZDTV2Cf5Ep9s7ttXfuE0V",
	"WuoISjsZdI85V8xl+B8oAua0VmXj7FQ0Mltfrf8/AAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
