package http

import (
	"context"
	"errors"
	"net/http"

	app "github.com/haribo/ozalid/apps/server/internal/app/catalogue"
	"github.com/haribo/ozalid/apps/server/internal/app/intake"
	"github.com/haribo/ozalid/apps/server/internal/domain/access"
	"github.com/haribo/ozalid/apps/server/internal/ports/http/openapi"
	"github.com/haribo/ozalid/internal/contract"
)

// CreateEdition takes a run's evidence into the book.
func (s *Server) CreateEdition(ctx context.Context, request openapi.CreateEditionRequestObject) (openapi.CreateEditionResponseObject, error) {
	// Evidence is what this book is for, so nothing writes any without saying
	// who it is. A token belongs to one project and reaches nothing outside it
	// (ADR 0018).
	if why, no := s.mayNot(ctx, request.Slug, access.WriteProject); no {
		if why.Status == http.StatusUnauthorized {
			return openapi.CreateEdition401ApplicationProblemPlusJSONResponse{
				UnauthenticatedApplicationProblemPlusJSONResponse: openapi.UnauthenticatedApplicationProblemPlusJSONResponse(why),
			}, nil
		}
		return openapi.CreateEdition403ApplicationProblemPlusJSONResponse{
			ForbiddenApplicationProblemPlusJSONResponse: openapi.ForbiddenApplicationProblemPlusJSONResponse(why),
		}, nil
	}

	result, err := s.intake.Take(ctx, request.Slug, toManifest(*request.Body))

	var missing *intake.MissingContent
	var notPNG *intake.NotPNG
	switch {
	case errors.As(err, &notPNG):
		// Naming the addresses lets the client fix the captures rather than
		// hunt for them. A lossy format cannot be compared, so a capture in one
		// could never answer "has it changed?" (product.md §2).
		return openapi.CreateEdition409ApplicationProblemPlusJSONResponse(
			notAPNG("Captures are compared byte for byte and pixel by pixel; a lossy format re-encodes the same screen differently every run. Re-capture the listed addresses as PNG.",
				notPNG.Hashes),
		), nil
	case errors.As(err, &missing):
		// Naming the addresses is the point: the client uploads exactly those
		// and pushes again, rather than re-sending an entire run.
		return openapi.CreateEdition409ApplicationProblemPlusJSONResponse(
			refusal("missing-content", "Content is missing", "Upload the listed addresses and push again.", missing.Hashes),
		), nil
	case errors.Is(err, intake.ErrUnknownCase):
		return openapi.CreateEdition409ApplicationProblemPlusJSONResponse(
			refusal("unknown-case", "The manifest names a case this project does not have",
				"A case id is generated by ozalid when the case is created. "+err.Error(), nil),
		), nil
	case errors.Is(err, intake.ErrDuplicateCase):
		return openapi.CreateEdition409ApplicationProblemPlusJSONResponse(
			refusal("duplicate-case", "The manifest names the same case twice",
				"Two sources writing to one case would corrupt it silently. "+err.Error(), nil),
		), nil
	case errors.Is(err, intake.ErrBlockedByPolicy):
		return openapi.CreateEdition409ApplicationProblemPlusJSONResponse(
			refusal("intake-blocked", "A review is still open", err.Error(), nil),
		), nil
	case errors.Is(err, intake.ErrEmptyManifest):
		return openapi.CreateEdition400ApplicationProblemPlusJSONResponse{
			BadRequestApplicationProblemPlusJSONResponse: openapi.BadRequestApplicationProblemPlusJSONResponse(
				problem("empty-manifest", "The manifest carries no case", http.StatusBadRequest, ""),
			),
		}, nil
	case errors.Is(err, app.ErrNotFound):
		return openapi.CreateEdition404ApplicationProblemPlusJSONResponse{
			NotFoundApplicationProblemPlusJSONResponse: notFound("project"),
		}, nil
	case err != nil:
		return nil, err
	}

	return openapi.CreateEdition201JSONResponse{
		EditionId:  result.EditionID,
		Cases:      result.Cases,
		Captures:   result.Captures,
		Recordings: result.Recordings,
	}, nil
}

// refusal builds the 409 payload, carrying the addresses to upload when that is
// what went wrong.
func refusal(kind, title, detail string, missing []string) openapi.IntakeRefused {
	p := problem(kind, title, http.StatusConflict, detail)
	out := openapi.IntakeRefused{
		Type:   p.Type,
		Title:  p.Title,
		Status: p.Status,
		Detail: p.Detail,
	}
	if len(missing) > 0 {
		out.MissingContent = &missing
	}
	return out
}

// notAPNG names the captures that have to be re-taken.
//
// A field of its own rather than `missingContent`: the store holds these bytes.
// A client told they are "missing" would upload them again and be refused
// again, which is the worst kind of error message — one that suggests a cure
// for the wrong disease.
func notAPNG(detail string, hashes []string) openapi.IntakeRefused {
	p := problem("not-a-png", "A capture is not a PNG", http.StatusConflict, detail)
	return openapi.IntakeRefused{
		Type: p.Type, Title: p.Title, Status: p.Status, Detail: p.Detail,
		NotAPng: &hashes,
	}
}

// toManifest turns the generated request body into the shape the CLI and the
// server both speak.
func toManifest(body openapi.Manifest) contract.Manifest {
	m := contract.Manifest{Cases: make([]contract.ManifestCase, 0, len(body.Cases))}
	if body.Revision != nil {
		m.Revision = *body.Revision
	}

	for _, c := range body.Cases {
		mc := contract.ManifestCase{ID: c.Id, Steps: make([]contract.ManifestStep, 0, len(c.Steps))}
		for _, st := range c.Steps {
			ms := contract.ManifestStep{Name: st.Name, Captures: make([]contract.ManifestCapture, 0, len(st.Captures))}
			for _, cap := range st.Captures {
				ms.Captures = append(ms.Captures, contract.ManifestCapture{
					Variant:    cap.Variant,
					Hash:       cap.Hash,
					Provenance: toProvenance(cap.Provenance),
				})
			}
			mc.Steps = append(mc.Steps, ms)
		}
		if c.Recordings != nil {
			for _, r := range *c.Recordings {
				mc.Recordings = append(mc.Recordings, contract.ManifestRecording{
					Variant: r.Variant, Hash: r.Hash,
				})
			}
		}
		m.Cases = append(m.Cases, mc)
	}
	return m
}

func toProvenance(p *openapi.Provenance) contract.Provenance {
	if p == nil {
		return contract.Provenance{}
	}
	return contract.Provenance{
		OS:             deref(p.Os),
		Browser:        deref(p.Browser),
		BrowserVersion: deref(p.BrowserVersion),
		Resolution:     deref(p.Resolution),
		EnvironmentID:  deref(p.EnvironmentId),
	}
}

func deref(s *string) string {
	if s == nil {
		return ""
	}
	return *s
}
